open-mmlab/mmsegmentation

.github/ISSUE_TEMPLATE/config.yml, docs/config.md, docs/getting_started.md, docs/tutorials/training_tricks.md, tools/convert_datasets/voc_aug.py
=> Fixed voc aug convert

docs/getting_started.md, docs/tutorials/training_tricks.md
=> Fixed training tricks

mmseg/datasets/pipelines/transforms.py
Fix '_resize_seg' bug in Resize data transforms
=> Fix '_resize_seg' bug in Resize data transforms

configs/fp16/README.md, docs/stat.py
=> update stat to classify papers

README.md, README_zh-CN.md
added mmocr link to chinese and english readme
=> add mmocr link

.github/pull_request_template.md
=> [Enhancement] Add PR template

MANIFEST.in
=> [Enhancement] Update metafiles

docs/get_started.md
=> [Fix] Fix torch version

docs/get_started.md
=> [Fix] Fix mmcv installation

docs/tutorials/config.md, docs_zh-CN/tutorials/config.md
=> [Fix] fix url error in config docs

.readthedocs.yml
Add more formats (pdf, epub) of documentation.
The format field in `readthedocs.yml` is modified.
=> [Enhancement] Output pdf and epub formats for readthedocs

.github/ISSUE_TEMPLATE/reimplementation_questions.md
Add template of reimplementation questions
=> [Enhancement] Add template of reimplementation questions 

docker/serve/Dockerfile
Dinamically install mmcv from PYTORCH and CUDA args
Use bash brace expansion https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html to dynamically install mmcv from docker ARGs …
=> [Enhancement] Add mmcv arg expansion

CITATION.cff, setup.py
=> Add MMSeg citation

README.md, README_zh-CN.md, docs/conf.py, docs_zh-CN/conf.py
add MMFlow link in README and conf.py
=> [Doc] add MMFlow link

README.md, README_zh-CN.md, docs/conf.py, docs_zh-CN/conf.py
add MMFewShot link in README and conf.py
=> [Doc] add MMFewShot link

docs_zh-CN/get_started.md
Fix error in the chinese get_started file
完成的安装脚本 ==> 完整的安装脚本
If this PR introduces a new feature, it is better to list some use …
=> [Docs] Update get_started.md

README.md, README_zh-CN.md, docs/conf.py, docs_zh-CN/conf.py
add MMHuman3D link in README and conf.py
=> [Doc] add MMHuman3D link

README.md, docs/model_zoo.md, docs_zh-CN/model_zoo.md
=> [Fix] MMHuman3D description and BiSeNetV2 FP16 hyperlink

README.md, README_zh-CN.md
Add MMSelfSup and MMRazor links in README.md.
=> [Doc] Add MMSelfSup and MMRazor links.

README.md, README_zh-CN.md
Add MMDeploy link in README.md.
=> [Doc] Add MMDeploy link.

README.md, README_zh-CN.md
Since OpenMMLab's website and platform is open to the public, we hope that the users in GitHub could visit our new website and platform. This will help the people interested in OpenMMLab to experience our algorithms and models visually, and learn more about our codebases.
Add some html lines on README.md and README-zh.md to show OpenMMLab website and platform link.
If so, please describe how it breaks the compatibility and how …
=> Add website and platform link

docs/en/useful_tools.md, docs/zh_cn/model_zoo.md, docs/zh_cn/train.md, docs/zh_cn/useful_tools.md
Fix typos in docs.
1. Fix img path typo in `useful_tools.md`
2. Fix typos `zh_cn/model_zoo.md`, and `zh_cn/train.md`
3. Add missing content in `zh_cn/useful_tools.md` to match `en/useful_tools.md`
If this PR introduces a new feature, it is better to list some use cases here, and …
=> [Docs] Fix typo

tools/deploy_test.py, tools/onnx2tensorrt.py, tools/pytorch2onnx.py
As title
ref: https://github.com/open-mmlab/mmclassification/pull/697
- add deprecation warning in tools/onnx2tensorrt.py
- add deprecation warning in tools/pytorch2onnx.py
No
3. If the modification has potential influence on …
=> Add deprecation message for deploy tool

README.md, README_zh-CN.md
As title
ref: https://github.com/open-mmlab/mmdetection/pull/7239
README file
2. The …
=> [Docs]Reorganizing OpenMMLab projects in readme

docs/en/changelog.md
Fix improper word.
modify docs/en/changelog.md
=> [Docs] fix typo in changelog

docs/en/tutorials/config.md, docs/zh_cn/tutorials/config.md
fix the config name style description
fix the config name style description
=> [Fix] fix the config name style description

README.md, README_zh-CN.md, docs/en/faq.md, docs/en/index.rst, docs/zh_cn/faq.md, docs/zh_cn/index.rst
Add faq document and describe how to know the number of GPUs needed to train a model.
Related PR: https://github.com/open-mmlab/mmdetection/pull/4045
FAQ in MMDet https://github.com/open-mmlab/mmdetection/blob/master/docs/en/faq.md.
Add faq document and describe how to know the number of GPUs needed to train a model.
=> [Docs] add faq document

.owners.yml
Add .owners.yml
1. Pre-commit or other linting tools are used to fix the potential …
=> [Enhancement] Add .owners.yml to mark daily issue shift

.owners.yml
=> [Fix] Update .owners.yml

demo/MMSegmentation_Tutorial.ipynb
The config file path is wrong.
Revise the directory for config file
No
4. The …
=> [Fix] the directory of cfg file in colab demo

.owners.yml
1. daily-shift-based is not suited for assignees < 5
1. .owners.yml
2. The modification is …
=> [Enhancement] Use round-robin

mmseg/ops/wrappers.py
Signed-off-by: FreyWang <wangwxyz@qq.com>
fix typo in condition
4. The documentation has been …
=> [Fix] bug of resize warning when align_corners is True

mmseg/apis/train.py, mmseg/datasets/samplers/distributed_sampler.py, mmseg/utils/__init__.py, mmseg/utils/util_distribution.py, tests/test_utils/test_util_distribution.py, tools/test.py, tools/train.py
MMSeg support PyTorch backend on MLU (with Cambricon PyTorch).
Support Cambricon MLU device for PyTorch backend.
mmseg/apis/train.py : for training on mlu device. 
tool/test.py : for test on mlu device.
mmseg/utils/distribution_util.py: some functions for building ddp according to different device.
related pr: https://github.com/open-mmlab/mmdetection/pull/7578
=> feat(mlu): Support PyTorch backend on MLU.

.github/workflows/lint.yml, .pre-commit-config.yaml, docs/zh_cn/get_started.md, docs/zh_cn/useful_tools.md
- Fix mdformat version to support python3.6 and refine documentation.
- Remove ruby from CI
ref: https://github.com/open-mmlab/mmcv/pull/2014
1. .github/workflows/lint.yml
2. .pre-commit-config.yaml
If this PR introduces a new feature, it is better to list some use cases here, and …
=> [Docs] Fix mdformat version to support python3.6 and remove ruby install

.github/workflows/build.yml, .github/workflows/test_mim.yml
Clean pillow version check
- .github/workflows/build.yml
- .github/workflows/test_mim.yml
None
=> [Enhancement] Clean pillow version check

LICENSES.md, README.md, README_zh-CN.md, mmseg/models/decode_heads/segformer_head.py
Ref PR: https://github.com/open-mmlab/mmcv/pull/956.
=> [Fix] Fix liscense of SegFormer

mmseg/utils/set_env.py
Correctly print the num_threads of opencv
=> fix OpenCV num_threads log

.circleci/config.yml, .circleci/docker/Dockerfile, .circleci/test.yml
=> set circle ci

mmseg/utils/set_env.py, tools/model_converters/beit2mmseg.py, tools/model_converters/mit2mmseg.py, tools/model_converters/stdc2mmseg.py, tools/model_converters/swin2mmseg.py, tools/model_converters/twins2mmseg.py, tools/model_converters/vit2mmseg.py, tools/model_converters/vitjax2mmseg.py
=> [Enhancement] Replace MMCV with MMEngine in convert model scripts

configs/_base_/default_runtime.py, mmseg/visualization/local_visualizer.py, tests/test_visualization/test_local_visualizer.py
Fix SegLocalVisualizer error if using GPU.
=> [Fix] Fix SegLocalVisualizer gt_sem_seg cuda tensor error

mmseg/datasets/dataset_wrappers.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Refactor several Data Transform
=> [Feature] Add P1 DataTransform

.circleci/test.yml
=> [Enhancement] Set up circle-ci on test-1.x branch

mmseg/models/backbones/stdc.py, mmseg/models/backbones/swin.py, mmseg/models/backbones/vit.py, mmseg/models/utils/embed.py
1. Use BaseModule from mmengine
1. mmseg/models/backbones/stdc.py
2. mmseg/models/backbones/swin.py
3. mmseg/models/backbones/vit.py
4. mmseg/models/utils/embed.py
=> [Fix] Import BaseModule from mmengine

mmseg/apis/inference.py
Need to deal with new checkpoint compatibility.
- Replace `mmcv.runner.load_checkpoint` with `mmengine.runner.load_checkpoint`.
- Set `dataset_info` according to ckpt version.
- Add `cfg_options` parameter to `init_model()`, default `None`.
=> [Enhancement] Support init_model API loading v1/v2 ckpts

.circleci/test.yml
1. CI failed without mmcls
1. .circleci/test.yml
=> [Enhancement] Add mmcls installation in mmseg dependencies

tools/analysis_tools/analyze_logs.py
=> [Fix] Fix wrong logic when create log dict in analyze_logs script

docs/en/api.rst, docs/zh_cn/api.rst
=> [Doc] Update API doc

.circleci/test.yml
1. circle ci will failed without mmcls installation
1. .circleci/test.yml
2. The modification …
=> [Enhancement] Add mmcls installation in circle ci

configs/cgnet/cgnet_512x1024_60k_cityscapes.py, configs/cgnet/cgnet_680x680_60k_cityscapes.py
1. Add `default_hooks` in cgnet
1. configs/cgnet/cgnet_512x1024_60k_cityscapes.py
2. configs/cgnet/cgnet_680x680_60k_cityscapes.py
1. Pre-commit or other linting tools are …
=> [Fix] Default hooks in cgnet config

mmseg/models/utils/res_layer.py
1. Using Sequential from mmcv will raise device bug
1. mmseg/models/utils/res_layer.py
2. The …
=> [Fix] Import Sequential from mmengine

configs/_base_/schedules/schedule_160k.py, configs/_base_/schedules/schedule_20k.py, configs/_base_/schedules/schedule_320k.py, configs/_base_/schedules/schedule_40k.py, configs/_base_/schedules/schedule_80k.py
1. As title
1. `configs/_base_/schedules/`
2. The modification is covered by complete unit …
=> [Fix] Add SegVisualizationHook in default hooks

tools/train.py
Support custom runner
`runner` will be built by `RUNNER` registry is `runner_type` is specific in cfg.
=> [Enhancement] Support custom runner

mmseg/datasets/basesegdataset.py
open-mmlab/mmcv#2179
Use  `mmengine` API instead of `mmcv`
=> [Fix] Fix basesegdataset

docs/en/user_guides/2_dataset_prepare.md
1. Rename dirname of scripts in `docs/en/user_guides/2_dataset_prepare.md`
2. Update links
=> [Refactor] Dataset tutorial for 1.x

docs/en/advanced_guides/transforms.md
docs/en/advanced_guides/transforms.md
=> [Refactor] Transforms tutorial for 1.x

docs/en/user_guides/1_config.md
Update the config to 1.x
`docs/en/user_guides/1_config.md`
=> [Refactor] Config tutorial for 1.x

mmseg/apis/inference.py, mmseg/datasets/transforms/formatting.py, mmseg/engine/hooks/visualization_hook.py, mmseg/evaluation/metrics/citys_metric.py, mmseg/evaluation/metrics/iou_metric.py, mmseg/models/data_preprocessor.py, mmseg/models/segmentors/base.py, mmseg/models/segmentors/cascade_encoder_decoder.py, mmseg/models/segmentors/encoder_decoder.py, mmseg/utils/misc.py, mmseg/visualization/local_visualizer.py, tests/test_config.py, tests/test_datasets/test_formatting.py, tests/test_datasets/test_tta.py, tests/test_engine/test_visualization_hook.py, tests/test_evaluation/test_metrics/test_iou_metric.py, tests/test_models/test_backbones/test_unet.py, tests/test_models/test_data_preprocessor.py, tests/test_models/test_forward.py, tests/test_visualization/test_local_visualizer.py, tools/analysis_tools/benchmark.py
1. As title
WIP
2. The modification is covered by complete unit tests. If not, please add more …
=> [Refactor] data flow

mmseg/models/data_preprocessor.py
=> [Fix] Fix inputs dtype convert in data preprocessor

tests/test_models/test_data_preprocessor.py, tests/test_models/test_forward.py
=> [Fix] Config name in ut

configs/_base_/default_runtime.py
1. Fix iterbased runner log processor
1. Add `log_processor = dict(by_epoch=False)` in configs/_base_/default_runtime.py
=> [Fix] Add `by_epoch=False` for log processor

tools/confusion_matrix.py
Just a short fix. For explanations, have a look at:
https://github.com/open-mmlab/mmsegmentation/issues/1969
=> [Fix] Unstable confusion matrix calculation

tools/analysis_tools/benchmark.py
as title
tools/analysis_tools/benchmark.py
=> [Fix] benckmark script

docs/en/user_guides/visualization.md
=> [Refactor] Add visualization tutorial for dev-1.x

docs/en/tutorials/config.md, docs/zh_cn/tutorials/config.md
To better use MMSegmentation functionality.
It's few one modify for add logger hooks to docs
=> logger hooks samples updated

docs/en/user_guides/3_inference.md, docs/en/user_guides/4_train_test.md
As title.
1. docs/en/user_guides/4_train_test.md
=> [Refactor] Inference and train tutorials for 1.x

mmseg/models/losses/__init__.py, mmseg/models/losses/tversky_loss.py, tests/test_models/test_losses/test_tversky_loss.py
Add Tversky Loss in dev-1.x branch.
Related PR: https://github.com/open-mmlab/mmsegmentation/pull/1986.
=> [Feature] Support Tversky Loss in dev-1.x branch

demo/image_demo.py, demo/video_demo.py, mmseg/apis/inference.py, tools/test.py, tools/train.py
=> [Fix] Revise input arguments of `show_result_pyplot`

tools/misc/browse_dataset.py
=> [Fix] browse dataset

mmseg/__init__.py, requirements/mminstall.txt, requirements/runtime.txt
=> [Enhancement]check version of codebase from openmmlab

mmseg/__init__.py, requirements/mminstall.txt
=> [Fix] Revise MMEngine mim version

docs/en/notes/changelog.md
=> Add changelog for MMSeg 1.0.0rc0

README.md
=> [Fix] links in README

.circleci/test.yml
=> [Fix] circle ci

README.md, README_zh-CN.md
As title.
- READEME.md
- README_zh-CN.md
=> [Doc] Introduce 1.x in readme

docs/en/user_guides/1_config.md
Update tutorial of configs.
- docs/en/user_guides/1_config.md
=> [Doc] Update config doc

docs/en/user_guides/3_inference.md, mmseg/apis/inference.py
as title.
- docs/en/user_guides/3_inference.md
=> [Doc] Update inference doc

.pre-commit-config.yaml, docs/en/get_started.md, docs/en/user_guides/visualization.md, mmseg/models/backbones/vit.py, mmseg/models/losses/focal_loss.py, setup.cfg
related pr https://github.com/open-mmlab/mmengine/pull/576
=> Upgrade pre commit hooks

.circleci/config.yml
=> [Fix] Ignore timm test in CircleCI

docs/en/get_started.md
Fix the installation commands in `get_started.md`
```shell
mim install 'mmcv>=2.0.0rc1'
mim install mmenigne
```
to
```shell
mim install mmengine
mim install "mmcv>=2.0.0rc1"
```
=> [Docs] Fix the installation commands in get_started.md

docs/en/advanced_guides/evaluation.md, mmseg/evaluation/metrics/citys_metric.py, mmseg/evaluation/metrics/iou_metric.py, tests/test_evaluation/test_metrics/test_citys_metric.py
As title.
- add `docs/en/advanced_guides/evaluation.md`
- fix typos in `mmseg/evaluation/metrics/iou_metric.py`
- remove parameters docstring and fix a bug in `mmseg/evaluation/metrics/citys_metric.py`
=> [Doc] Add evaluation doc

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
=> [CI] Fix win ci

configs/mobilenet_v2/mobilenet-v2-d8_deeplabv3_4xb2-80k_cityscapes-512x1024.py, configs/mobilenet_v2/mobilenet-v2-d8_deeplabv3_4xb4-160k_ade20k-512x512.py, configs/mobilenet_v2/mobilenet-v2-d8_deeplabv3plus_4xb2-80k_cityscapes-512x1024.py, configs/mobilenet_v2/mobilenet-v2-d8_deeplabv3plus_4xb4-160k_ade20k-512x512.py, configs/mobilenet_v2/mobilenet-v2-d8_fcn_4xb2-80k_cityscapes-512x1024.py, configs/mobilenet_v2/mobilenet-v2-d8_fcn_4xb4-160k_ade20k-512x512.py, configs/mobilenet_v2/mobilenet-v2-d8_pspnet_4xb2-80k_cityscapes-512x1024.py, configs/mobilenet_v2/mobilenet-v2-d8_pspnet_4xb4-160k_ade20k-512x512.py
=> [Fix]Use syncbn in mobilenet_v2

mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
1. Generate Edge for LIP dataset in CE2P
1. Add `GenerateEdge`
No
Use for CE2P algorithm
=> [Feature]Generate Edge for dataset

README.md, README_zh-CN.md
Add MMYOLO to README of branch `dev-1.x`
=> [Doc] Add MMYOLO to README of dev-1.x

README.md, README_zh-CN.md
=> Add MMEval projects like in README

.pre-commit-config.yaml
fix for pre-commit
flake8 no longer exist in gitlab.
changing it to github fix the problem?
If this PR introduces a new feature, …
=> gitlab.com/pycqa/flake8 no longer exists

docs/zh_cn/user_guides/visualization.md
=> [Doc] Translate the visualization.md

docs/zh_cn/advanced_guides/datasets.md
Add `datasets.md` documentation in dev-1.x branch, the english version pr would be created after this pr being merged.
=> [Doc] Add ZN datasets.md in dev-1.x

docs/zh_cn/get_started.md
=> CodeCamp #1565 [Doc] update the Chinese version of `get_started.md`

configs/pspnet/README.md
Add pspnet model structure based on the 超级视客营 activity.
Add pspnet model structure graph in pspnet config readme.
=> CodeCamp #1558 [Doc] Add pspnet model structure graph

docs/en/migration/interface.md, docs/en/user_guides/4_train_test.md
=> [Doc] Update TTA to migration doc

README.md
Add link for high quality synthetic face occlusion dataset.
readme.md
1. Pre-commit or other linting tools are …
=> Add high quality synthetic face occlusion dataset link to readme.

projects/isnet/README.md
As title. 
- projects/isnet/README.md
=> [Doc] Add checklist of ISNet

.circleci/test.yml, .github/workflows/merge_stage_test.yml
as title
1. .circleci/test.yml
2. .github/workflows/merge_stage_test.yml
=> [CI] Remove test py3.6

docs/en/user_guides/2_dataset_prepare.md, docs/zh_cn/user_guides/2_dataset_prepare.md
- Add Chinese version of Synapse dataset preparation.
- Modify all `，` and `。` to `,` and `.` in `docs/zh_cn/user_guides/2_dataset_prepare.md`.
=> [Doc] Update ZN dataset preparation of Synapse

mmseg/core/evaluation/class_names.py
support get_classes, get_palette for Occluded Face dataset. 
add occludedface_classes()
add occludedface_palette()
modified dataset_aliases
=> Support for occludedface for external use

docs/en/api.rst, docs/zh_cn/api.rst, requirements/readthedocs.txt
As title.
- docs/en/api.rst
- docs/zh_cn/api.rst
- add `scipy` to readthedocs requirement.
=> [Doc] Fix API document

demo/image_demo.py
Fix: https://github.com/open-mmlab/mmsegmentation/issues/2478
=> [Fix] Fix no revert_sync_batchnorm in image_demo of master branch

docs/zh_cn/advanced_guides/datasets.md
Ref: https://github.com/open-mmlab/mmsegmentation/pull/2464#discussion_r1072211706
=> [Fix][Doc] Fix link of preprocessing and order of operations in ZN dataset.md doc.

docs/zh_cn/advanced_guides/customize_runtime.md
Old PR: https://github.com/open-mmlab/mmsegmentation/pull/2169
=> [Doc] Add ZN Customized_runtime Doc in dev-1.x

mmseg/apis/inference.py, mmseg/visualization/local_visualizer.py
=> [Fix] Fix inference api and support setting palette to SegLocalVisualizer

docs/en/advanced_guides/datasets.md
Add English version of `datasets.md`, the Chinese version is in https://github.com/open-mmlab/mmsegmentation/pull/2387.
=> [Doc] Add EN datasets.md in dev-1.x

.pre-commit-config.yaml
https://github.com/open-mmlab/mmeval/pull/85
=> [CI] Upgrade the version of isort to fix lint error in master branch

.github/workflows/merge_stage_test.yml
=> [Fix]Fix mmcv version 2.0.0rc3 for win test

docs/zh_cn/tutorials/config.md
=> Fix ch-zn doc.md error.

docs/en/device/npu.md, docs/zh_cn/device/npu.md
Motivation
add NPU results.
Modification
add docs/en/device/npu.md and docs/zh_cn/device/npu.md that accompanies the submission results.
=> [NPU] add npu result

docs/en/migration/package.md
=> [Doc] fix api name error in the migration doc

docs/en/train.md
Just fixes a small typo in the example.
=> Fix work-dir flag name in example

docs/zh_cn/get_started.md
=> Docs: change MMPose to MMSegmentation

docs/zh_cn/advanced_guides/add_transforms.md
=> [Doc] Add zh_cn add_transforms doc

docs/en/advanced_guides/models.md, docs/zh_cn/advanced_guides/models.md
=> [Doc] Add zh_cn models doc and fix en doc typo

mmseg/datasets/transforms/formatting.py, tests/test_datasets/test_formatting.py
=> [Fix] Format shape check

docs/zh_cn/notes/faq.md
=> [Docs] Update zh_CN faq.md

docs/en/advanced_guides/add_datasets.md, docs/zh_cn/advanced_guides/add_datasets.md
=> [Doc] Update add_datasets docs

docs/en/inference.md
https://github.com/open-mmlab/mmsegmentation/issues/2779
=> [Doc] Fix inference doc

docs/zh_cn/notes/faq.md
=> [Doc] Fix invalid links and standardize Chinese and English punctuation marks at zh_CN faq.md 

README.md, README_zh-CN.md
https://github.com/open-mmlab/mmdetection3d/pull/2389
=> [Doc] Add more social networking links

tools/test.py, tools/train.py
=> [Fix] Fix accepting an unexpected argument local-rank in PyTorch 2.0 (master)

docs/en/migration/interface.md, docs/zh_cn/migration/interface.md, docs/zh_cn/migration/package.md
=> Fix migration doc

README.md, README_zh-CN.md
=> [Doc] Update links in README

.circleci/config.yml, .circleci/test.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml, .github/workflows/test_mim.yml
https://github.com/actions/runner-images/issues/6002
=> [CI] Update ci image

.circleci/test.yml, .github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
=> [CI] update mmdet dependency

README.md, README_zh-CN.md, docs/en/advanced_guides/datasets.md, docs/en/switch_language.md, docs/zh_cn/advanced_guides/datasets.md, projects/faq.md
=> [Doc] update doc link

docs/en/user_guides/1_config.md
Typo in tutorial-1.
A example -> An example.
=> Fix typo in tutorial-1

docs/zh_cn/overview.md
=> [Fix] modify links in `overview.md`

mmseg/models/losses/cross_entropy_loss.py
fix squeeze error when N=1 and C=1
fix squeeze error when N=1 and C=1
2. The modification is …
=> [Fix] fix squeeze error when N=1 and C=1

README.md, README_zh-CN.md
Update repo information and URLs in README.
=> [Doc] update repo list in README

docs/zh_cn/advanced_guides/models.md
Complete task 11: translate the model documentation from English to Chinese.
To translate the model documentation from English to Chinese. However, there is one, so I improve it a bit.
=> [Doc] Update the translation of models.

README.md, README_zh-CN.md, tools/test.py
=> Fix typo in tools/test.py

README.md, README_zh-CN.md, configs/ddrnet/README.md
Ref: https://github.com/ydhongHIT/DDRNet#citation
=> [Fix] Fix DDRNet readme

docs/en/device/npu.md, docs/zh_cn/device/npu_zh.md
Fix uprenet config issue in readme.
Fix npu.md.
None.
None.
=> [Fix]Fix config issue in readme.

.circleci/test.yml
=> [CI] Fix mmdet version

README.md, README_zh-CN.md, docker/Dockerfile
=> [Docker] update Dockerfile libgl1-mesa-dev

mmseg/models/backbones/swin.py
Enhance pretrained SwinTransformer loading when setting non-standard backbone `depths`.
Enhance pretrained SwinTransformer loading when setting non-standard backbone `depths`.
If this PR introduces a new feature, it is better to list some use cases here, and update the …
=> [Feature] enhance swin pretrained model loading

MANIFEST.in, dataset-index.yml, setup.py
=> [Feature] support mim download dataset

mmseg/models/data_preprocessor.py, mmseg/models/segmentors/encoder_decoder.py
https://github.com/open-mmlab/mmsegmentation/issues/3181 https://github.com/open-mmlab/mmsegmentation/issues/2965 https://github.com/open-mmlab/mmsegmentation/issues/2644 https://github.com/open-mmlab/mmsegmentation/issues/1645 https://github.com/open-mmlab/mmsegmentation/issues/1444 https://github.com/open-mmlab/mmsegmentation/issues/1370 https://github.com/open-mmlab/mmsegmentation/issues/125
Remove the assertion at data_preprocessor
Does the modification introduce changes that break the backward-compatibility of the …
=> [Enhancement] Remove batch inference assertion

projects/pp_mobileseg/README.md, projects/pp_mobileseg/inference_onnx.py
Add a model deployment example.
Add an inference script and update the README.
None
In README.
=> [Project] Add pp_mobileseg onnx inference demo

configs/vpd/vpd_sd_4xb8-25k_nyu-480x480.py, mmseg/datasets/transforms/transforms.py
=> [Fix] Fix training of VPD model

README.md, README_zh-CN.md
Add OpenXLab Badge to share official applications, community applications and ecological applications based on MMSegmentation in the OpenXLab platform.
Added OpenXLab Badge in ReadME（English & Chinese）
If this PR introduces a new feature, it is better to list some use cases here, …
=> [Doc] add openxlab badge

mmseg/models/backbones/vpd.py, tools/analysis_tools/visualization_cam.py
=> [Fix] fix import error raised by ldm

mmseg/apis/mmseg_inferencer.py
see [here](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/visualization/local_visualizer.py#L223C13-L223C13)
=> [Fix] fix wrong variables passing for `set_dataset_meta`

mmseg/apis/inference.py
https://github.com/open-mmlab/mmsegmentation/issues/3384
- mmseg/apis/inference.py
=> [Fix] Fix init api

docs/en/advanced_guides/add_datasets.md, docs/zh_cn/advanced_guides/add_datasets.md
=> [Doc] fix typo in `add_datasets` docs

README.md, README_zh-CN.md
=> [Docs] Optimize Home page format

docs/en/.readthedocs.yml, docs/zh_cn/.readthedocs.yml
ref: https://github.com/InternLM/lmdeploy/pull/1245
=> [Docs] Fix readthedocs
