mmseg/models/segmentors/base.py
```
Traceback` (most recent call last):  File "tools/demo.py", line 21, in <module>
model.show_result(img, result, out_file='demo_res/'+img)
File 'mmsegmentation/mmseg/models/segmentors/base.py", line 247, in show_result
assert palette.shape[0] == len(self.CLASSES)
AttributeError: 'list' object has no attribute 'shape'
```
=> Fix palette type.

docs/getting_started.md, tools/train.py
The `load-from` option exists both in api and docs, but not in the training script.
This PR fixes that.
=> Add load-from flag

docs/getting_started.md, mmseg/apis/test.py, mmseg/datasets/cityscapes.py, mmseg/models/segmentors/encoder_decoder.py, tools/train.py
This PR fixed sliding inference with ONNX. 
Also fixed #89
=> Fixed slide inference

mmseg/apis/test.py
=> Update mmseg/apis/test.py to fix the problem of if statement.

mmseg/models/backbones/hrnet.py, mmseg/ops/__init__.py, mmseg/ops/wrappers.py, tools/pytorch2onnx.py
As ONNX does not support using nn.Upsample, we have to use our customized Upsample Module which is a simple wrapper of F.interpolate.
Besides, pytorch2onnx.py does not support models with multiple decode heads (like ocrnet), we support these models in this version.
Fixed #97
=> Onnx upsample

mmseg/core/evaluation/mean_iou.py, tests/test_mean_iou.py
Reproduce
```python
In [4]: import torch
...: targets = torch.randint(0, 5, size=(12,3,256,256))
...: preds = torch.randint(0,4, size=(12,3,256,256))
...: mean_iou(preds, targets,7, ignore_index=255)
/usr/local/bin/ipython:63: RuntimeWarning: invalid value encountered in true_divide
[471730. 473621. 472044. 471450. 470451.      0.      0.]
/usr/local/bin/ipython:65: RuntimeWarning: invalid value encountered in true_divide
Out[4]:
(0.20025168524848092,
array([0.25013461, 0.25040275, 0.25065036, 0.2493223 , 0.     ,    nan,        nan]),
array([0.12510297, 0.12543045, 0.12530315, 0.1246835 , 0.        ,    nan,        nan]))
```
new result:
```python
In [6]: import torch
...: targets = torch.randint(0, 5, size=(12,3,256,256))
...: preds = torch.randint(0,4, size=(12,3,256,256))
...: …
```
=> fix acc and iou compute nan problem

mmseg/models/segmentors/encoder_decoder.py
Our TRT backend only support 4D output. So we have to unsqueeze the output to make sure it is 4D ([1, batch, H, W])
=> add support for 4D output

mmseg/datasets/custom.py
Without using these prefixes, `single_gpu_test` with `output_dir` enabled will overwrite the original images because `ori_filename`  is being set to the absolute path to the image.
=> Use img_prefix and seg_prefix for loading

mmseg/apis/inference.py
=> Fix cpu inference

mmseg/datasets/custom.py, tests/test_data/test_dataset.py
`CustomDataset` currently supports setting `classes` via config file, covering two use cases: using your own dataset and using a subset of existing dataset. However because of how it's currently handled, the palette only covers the subset case. 
This P.R. includes the option to set `palette` via configuration files and automatically creates one with random colors when no palette is given.
=> Support custom palette

docs/getting_started.md
After trying myself and checking the code, I believe the actual flag expected to use for testing is --eval-options instead of --options.
=> update test command: --eval-options -> --options to set extra options

configs/_base_/models/fast_scnn.py, configs/fastscnn/fast_scnn_4x8_80k_lr0.12_cityscapes.py, mmseg/models/decode_heads/decode_head.py, mmseg/models/losses/cross_entropy_loss.py, tests/test_models/test_losses.py
=> [Enhancement] Support ignore_index for sigmoid BCE

mmseg/datasets/pipelines/__init__.py
=> [Bug Fix] Add missing transforms in __init__.py

mmseg/datasets/pipelines/loading.py
Fix doctring misspelled in `loading.py`.
=> [fix]: fix docstring

mmseg/apis/inference.py, tests/test_inference.py
When running test time augmentation(TTA) on CPU, it will raise this Error:    `num of augmentations (2) != num of image meta (1)`. The test log is here: https://github.com/youqingxiaozhua/mmsegmentation/actions/runs/381178359
The reason is the  `inference_segmentor` function in `mmseg/apis/inference.py` always returns the first image meta when the model's parameters are located on CPU, which is not suited for augmentation cases.
=> Bugfix: num of augmentations and image meta not match when run TTA on CPU

configs/apcnet/apcnet_r50-d8_512x512_160k_ade20k.py, configs/apcnet/apcnet_r50-d8_512x512_80k_ade20k.py, configs/deeplabv3/deeplabv3_r50-d8_512x512_160k_ade20k.py, configs/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k.py, configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_160k_ade20k.py, configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_80k_ade20k.py, configs/dmnet/dmnet_r50-d8_512x512_160k_ade20k.py, configs/dmnet/dmnet_r50-d8_512x512_80k_ade20k.py, configs/fcn/fcn_r50-d8_512x512_160k_ade20k.py, configs/fcn/fcn_r50-d8_512x512_80k_ade20k.py, configs/psanet/psanet_r50-d8_512x512_160k_ade20k.py, configs/psanet/psanet_r50-d8_512x512_80k_ade20k.py, configs/pspnet/pspnet_r50-d8_512x512_160k_ade20k.py, configs/pspnet/pspnet_r50-d8_512x512_80k_ade20k.py, configs/upernet/upernet_r50_512x512_160k_ade20k.py, configs/upernet/upernet_r50_512x512_80k_ade20k.py, mmseg/core/evaluation/metrics.py
=> [Bug fix] Fixed ADE20k test

docs/useful_tools.md, setup.cfg, tools/analyze_logs.py
Support plot logs by matplotlib.
=> add plot_logs tool

demo/image_demo.py, docs/get_started.md, mmseg/apis/inference.py, mmseg/apis/test.py, mmseg/models/segmentors/base.py, tools/test.py
Add new optional argument to `show_result` for changing the opacity of the painted segmentation map. The default value maintains the previous behavior. Places using `show_result` had been updated exposing the new argument.
=> [Feature] Add opacity option to show_result

mmseg/models/losses/dice_loss.py, tests/test_models/test_losses.py
=> [Bug fixed]Fix dice_loss errors

mmseg/datasets/custom.py
Add each class metric to the `.log` and `.log.json`. 
Each class metric format is `metric.class:0.43`, such as `IoU.Persion: 0.2432`, `Acc:Persion: 0.5434`. 
This PR Fix the iussue #397 
For now the output should be like this:
```
2021-03-27 23:50:31,241 - mmseg - INFO - Iter(val) [10] mIoU: 0.0492, mAcc: 0.0714, aAcc: 0.6881, IoU.background: 0.6881, IoU.aeroplane: 0.0000, IoU.bicycle: 0.0000, IoU.bird: nan, IoU.boat: 0.0000, IoU.bottle: 0.0000, IoU.bus: nan, IoU.car: 0.0000, IoU.cat: nan, IoU.chair: 0.0000, IoU.cow: 0.0000, IoU.diningtable: nan, IoU.dog: nan, IoU.horse: 0.0000, IoU.motorbike: nan, IoU.person: 0.0000, IoU.pottedplant: nan, IoU.sheep: 0.0000, IoU.sofa: 0.0000, IoU.train: 0.0000, IoU.tvmonitor: 0.0000, Acc.background: 1.0000, Acc.aeroplane: 0.0000, Acc.bicycle: 0.0000, …
```
=> Include each class metrics in logs

mmseg/apis/test.py, mmseg/core/evaluation/metrics.py, mmseg/core/seg/sampler/base_pixel_sampler.py, mmseg/datasets/custom.py, mmseg/datasets/pipelines/transforms.py, mmseg/models/backbones/cgnet.py, mmseg/models/backbones/hrnet.py, mmseg/models/backbones/mobilenet_v3.py, mmseg/models/backbones/unet.py, mmseg/models/decode_heads/apc_head.py, mmseg/models/decode_heads/dm_head.py, mmseg/models/decode_heads/gc_head.py, mmseg/models/losses/lovasz_loss.py, mmseg/models/utils/inverted_residual.py, mmseg/models/utils/se_layer.py, mmseg/models/utils/up_conv_block.py, mmseg/ops/encoding.py, tests/test_models/test_unet.py
Signed-off-by: lizz <lizz@sensetime.com>
=> Fix typo: upsampe_cfg -> upsample_cfg

tools/print_config.py
The `tools/print_config.py` can only print the config.py.
The new args `--graph` will print and save the model graph to `example-graph.txt`.
```
Model graph:
EncoderDecoder(
(backbone): ResNetV1c(
(stem): Sequential(
(0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
(1): SyncBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
(2): ReLU(inplace=True)
(3): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
(4): SyncBatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
(5): ReLU(inplace=True)
(6): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
(7): SyncBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
(8): ReLU(inplace=True)
) …
```
=> add print model graph args for tools/print_config.py

docs/useful_tools.md, mmseg/apis/inference.py, mmseg/models/segmentors/encoder_decoder.py, mmseg/ops/wrappers.py, tools/pytorch2onnx.py
Hi
This PR adds dynamic export and visualize of pytorch2onnx.
Tested on FCN, PSPNet, DeeplabV3, DeeplabV3+.
Note that dynamic shape support of PSPNet is not fully supported cause ONNX does not support dynamic export of AdaptiveAvgPool.
=> add dynamic export and visualize to pytorch2onnx

mmseg/core/evaluation/metrics.py, tests/test_metrics.py
1. Fix the bug about torch.histc function. When setting arg:max same as arg:bins for torch.histc, some channel of mIoU may be nan.
2. Modify tests/test_metrics.py. Add some abnormal num_classes test cases.
Single-scale, No flip, mIoU test result:
| model | num classes | Lr schd | after fix | before fix | readme |
| :--: | :--: | :--: | :--: | :--: | :--: |
| HRNetV2-W48(new) | 59 | 40000 | 50.37 | 50.13 | None |
| HRNetV2-w48(new) | 59 | 80000 | 51.12 | 50.85 | None |
| HRNetV2-W48(new) | 60 | 40000 | 45.55 | 45.55 | 45.14 |
| HRNetV2-W48(old) | 60 | 40000 | 45.14 | 45.14 | 45.14 |
before fix: 
* keyboard=nan
Single-scale, No flip, mIoU test result:
| model | Crop Size | Lr schd | after fix | before fix | readme |
| :--: | :--: | :--: | :--: | :--: | :--: |
| HRNetV2-W48(old) | 512x1024 | …
=> Fix mIoU calculatiton range

mmseg/models/segmentors/__init__.py
Hi, I am Ziyi, a developer of mmdet3d, and I am planning to implement 3D segmentors for point cloud scene segmentation. To inherit BaseSegmentor3D from BaseSegmentor, I add the import of BaseSegmentor to `__init__.py` of `segmentors/`. Thanks.
=> [Enhance] Add BaseSegmentor import to help support MMDet3D

mmseg/apis/test.py, mmseg/models/segmentors/base.py, tests/test_eval_hook.py
Hi, I am Ziyi, a developer from MMDet3D. In order to train/test 3D seg algorithms, I need to call functions from MMSeg. However, some functions in MMSeg calls `data['img']`, which causes `KeyError` because we don't have `img`. I replace these calling with some workarounds and make it compatibility with MMDet3D. Hope you can approve it. Thanks.
=> [Enhance] Replace data_dict calling 'img' key to support MMDet3D

mmseg/models/losses/cross_entropy_loss.py, mmseg/models/losses/dice_loss.py, mmseg/models/losses/lovasz_loss.py, mmseg/models/losses/utils.py, tests/test_models/test_losses/test_ce_loss.py, tests/test_models/test_losses/test_dice_loss.py, tests/test_models/test_losses/test_lovasz_loss.py
Hi, I am Ziyi, a developer from MMDet3D. Currently we are implementing 3D segmentation models, which require using loss functions from MMSeg (e.g. CrossEntropy). It's very common to use class_weight in 3D Seg, and in some scenarios we need to load class_weight from files. So I modify the code and support this feature. Hope you can approve it. Thanks.
=> [Enhance] Support reading class_weight from file in loss functions to help MMDet3D

mmseg/models/backbones/vit.py, tests/test_models/test_backbones/test_vit.py
Add arg:final_reshape for vit to control if converting output feature information from NLC to NCHW.
=> Add option for output shape of ViT

mmseg/models/backbones/mobilenet_v2.py
Change ‘range(0, 8)’ to 'range(0, 7)' in the error message.
=> Fix typo in mobilenet_v2

mmseg/apis/test.py
MMDet3D data doesn't have `'img'` term. Instead, we infer batch_size from `len(result)`. MMDet also adopts this fashion [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/test.py#L105).
=> [Enhance] Infer batch_size using len(result) to support MMDet3D

mmseg/models/backbones/vit.py, mmseg/models/necks/multilevel_neck.py
[Ref implementation](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py#L378)
Add `'model'` case at `init_weights()`function in vit backbone.
In addition, delete unnecessary code in multilevel neck.
=> [fix] fix loading deit weights

docs/useful_tools.md, tools/onnx2tensorrt.py
Hi
This PR adds tools to convert the ONNX model to TensorRT.
FCN, PSPNet, Deeplabv3, and Deeplabv3+ have been tested.
Note that all models are tested under `whole mode`. `slide mode` might not support for now.
=> [Feature] add onnx to tensorrt conversion tools.

tools/pytorch2onnx.py
Hi
This PR fixes `shape mismatch` when verifying the `whole mode` model in `pytorch2onnx`.
=> fix verify bugs

README.md
https://openaccess.thecvf.com/CVPR2017 does not contain DeepLabV3
=> DeepLab V3 did not present in CVPR 2017

mmseg/core/evaluation/eval_hooks.py, tools/test.py, tools/train.py
Change `eval_hooks.py`, able to use `save_best` while training.
=> [feature]: Able to use save_best option

.github/workflows/build.yml
1. Add torch_version and cuda_version into `matrix`;
2. Add 'Install MMCV_CPU' CI item to install mmcv-full in cpu environment;
3. Add 'Install MMCV_GPU' CI item to install mmcv-full in gpu environment;
=> [Feature] Move 'Install MMCV' to a independent CI item.

README.md, docs/get_started.md
=> [Fix] Fix typo and link

docker/Dockerfile
This PR adds a couple of fixes to Dockerfile.
1. Fix typo in url to git repo in Dockerfile, while cloning
2. Fix pip install command to use requirements file in top level dir (requirements/build.txt does not exist)
Fixes #595
=> Add fixes to Dockerfile

mmseg/models/backbones/vit.py, mmseg/models/utils/timm_convert.py, tests/test_models/test_backbones/test_vit.py
1. Fix some new style parameters init bug for vit.
2. Add some unit test for vit to improve code cov.
=> [Fix] Fix some vit init bugs

configs/ann/metafile.yml, configs/apcnet/metafile.yml, configs/ccnet/metafile.yml, configs/cgnet/metafile.yml, configs/danet/metafile.yml, configs/deeplabv3/metafile.yml, configs/deeplabv3plus/metafile.yml, configs/dmnet/metafile.yml, configs/dnlnet/metafile.yml, configs/emanet/metafile.yml, configs/encnet/metafile.yml, configs/fastscnn/metafile.yml, configs/fcn/metafile.yml, configs/fp16/metafile.yml, configs/gcnet/metafile.yml, configs/hrnet/metafile.yml, configs/mobilenet_v2/metafile.yml, configs/mobilenet_v3/metafile.yml, configs/nonlocal_net/metafile.yml, configs/ocrnet/metafile.yml, configs/point_rend/metafile.yml, configs/psanet/metafile.yml, configs/pspnet/metafile.yml, configs/resnest/metafile.yml, configs/sem_fpn/metafile.yml, configs/unet/metafile.yml, configs/upernet/metafile.yml
Change inference time from 'fps' to 'ms/im' in metafile to meet the requirement of PWC Model-index Format.
=> [Enhancement] Change inference time from 'fps' to 'ms/im' in metafile

README.md, README_zh-CN.md, mmseg/models/decode_heads/setr_up_head.py, tests/test_models/test_heads/test_setr_up_head.py
1. The lack of SETR & ViT in the model list. 
2. The SETRUPHead still use deprecated init_weights.
1.  Add SETR & ViT url in the main readme doc.
2. Refactor init of SETRUPHead.
=> [Fix] Add setr & vit msg.

docs/get_started.md, mmseg/__init__.py
`init_weight`  in `BaseModule` has been changed to `init_weights` when MMCV >= V1.3.2
Fix #653 
[get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/get_started.md#prerequisites)
No
=> [Fix] Fix mmcv version compatible in get_started.md

mmseg/core/evaluation/eval_hooks.py
=> [Fix] Fix efficient test bug

mmseg/datasets/builder.py
The limited resource [adjustment](https://github.com/open-mmlab/mmpose/blob/master/mmpose/datasets/builder.py#L13-L19)  will reduce the base file-open soft limit to 4096. Sometimes it will result in `'OSError: [Error 24] Too many open files' during training process` when large file-open needed (>4096).
=> [Fix] Update resource limit

mmseg/models/backbones/resnet.py
Here is the quick fix for resnet backbone init_cfg option I talked about in #695
=> Fix init_cfg in resnet backbone

docs/conf.py, requirements/readthedocs.txt
readthedocs api page failed due to mmcv import. 
Add mock imports.
=> [Doc] Fixed doc api display

.gitignore, MANIFEST.in, README.md, setup.py
- add MIM introduction in README
- modify setup.py to support mim as mmseg entry point
=> [Feature] support mim

tools/analyze_logs.py
In some log files, iterations number is not correct, that may cause drawing unnecessary lines at log graph.
Add `pre_iter` to record pre-inters number at for loop. 
4. The documentation has …
=> [Fix] fix analyze log script

mmseg/models/backbones/swin.py, mmseg/models/backbones/unet.py, mmseg/models/backbones/vit.py, mmseg/models/decode_heads/fpn_head.py, mmseg/models/decode_heads/setr_mla_head.py, mmseg/models/decode_heads/setr_up_head.py, mmseg/models/necks/fpn.py, mmseg/models/necks/multilevel_neck.py, tests/test_models/test_backbones/test_unet.py, tools/deploy_test.py, tools/pytorch2onnx.py
I am having problems to export mmsegmentation -> onnx -> tensorflow. There is a know limitation related with interpolate (see [here](https://github.com/onnx/onnx-tensorflow/issues/632#issuecomment-743717023)). I tried to fix mmseg.ops.resize behavior to always use `align_corners` but I realize some modules are still using torch `F.interpolate`. 
`
Use mmseg resize wrapper for all operations.
If so, please describe how it breaks …
=> [Fix] Replace interpolate with resize

mmseg/models/backbones/resnet.py
Some `args` of ResNet in the docstring are missing.
Some default values of `args` are also missing
Docstring of ResNet
No
=> [Enhancement] Refine the docstring of ResNet

mmseg/models/backbones/hrnet.py, tests/test_models/test_backbones/test_hrnet.py
Add new feature to support HRNet frozen stage like ResNet.
- Add new parameter `frozen_stages` for `HRNet`.
- Add new method `_freeze_stages` for `HRNet`.
- Add new test function `test_hrnet_backbone` to test the frozen_stages.
No.
1. use the frozen_stages from code
```python
model = HRNet(extra, frozen_stages=1) # frozen the first stage
```
2. use the frozen_stages from config
```python
_base_ = './fcn_hr18_512x512_20k_voc12aug.py'
model = dict(
pretrained='open-mmlab://msra/hrnetv2_w18_small',
backbone=dict(
frozen_stages=1,
extra=dict(
stage1=dict(num_blocks=(2, )),
stage2=dict(num_blocks=(2, 2)),
stage3=dict(num_modules=3, num_blocks=(2, 2, 2)),
stage4=dict(num_modules=2, num_blocks=(2, 2, 2, 2)))))
```
1. Pre-commit used.
2. The modification is covered by complete unit tests.
3. The …
=> [Enhancement] Support hrnet frozen stage

configs/swin/README.md
Fix the README of Swin.
Motivation
Failed to build [Model Zoo Statistics](https://mmsegmentation.readthedocs.io/en/latest/).
[Fixed](https://mmsegmentation--764.org.readthedocs.build/en/764/modelzoo_statistics.html) in this PR.
=> [Fix] Fix the README of Swin 

configs/ann/README.md
Modification:
From 
```latex
@inproceedings{annn,
author    = {Zhen Zhu and
Mengde Xu and
Song Bai and
Tengteng Huang and
Xiang Bai},
title     = {Asymmetric Non-local Neural Networks for Semantic Segmentation},
booktitle={International Conference on Computer Vision},
year      = {2019},
url       = {http://arxiv.org/abs/1908.07678},
}
```
to
```latex
@inproceedings{zhu2019asymmetric,
title={Asymmetric non-local neural networks for semantic segmentation},
author={Zhu, Zhen and Xu, Mengde and Bai, Song and Huang, Tengteng and Bai, Xiang},
booktitle={Proceedings of the IEEE/CVF International Conference on Computer Vision},
pages={593--602},
year={2019}
}
```
=> [Fix] Citations format of ANN

mmseg/apis/train.py
If the priority of EvalHook is higher than IterTimerHook, it will cause `KeyError: 'data_time'` (#758).
Since the `time` key will add to the output of log_buffer after IterTimeHook, the TextLoggerHook will print the `time` and  `data_time` at the same time.
This PR is based on https://github.com/open-mmlab/mmcv/pull/1252.
Set the priority of EvalHook to LOW.
No.
=> [Fix] Fix the log error 

tools/deploy_test.py
This PR fix cpu support for deploy test on ONNX Runtime.
`onnxruntime` could be used instead of `onnxruntime-gpu`.
input tensor would be send to host if cuda device is not a available.
=> [Fix] Support CPU deploy test for ONNX Runtime

mmseg/datasets/custom.py
ensure items in dataset have the same order across multi machine
sort items according to their filenames when using scandir
=> [Fix] Ensure items in dataset have the same order across multi machine

requirements/docs.txt
As recommended by [readthedocs](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies), we should fix the version of sphinx.
Fix the version of sphinx
=> [Docs] Fix sphinx version

mmseg/datasets/pipelines/formating.py, mmseg/models/backbones/cgnet.py, mmseg/models/backbones/fast_scnn.py, mmseg/models/backbones/hrnet.py, mmseg/models/backbones/mit.py, mmseg/models/backbones/mobilenet_v2.py, mmseg/models/backbones/resnest.py, mmseg/models/backbones/resnet.py, mmseg/models/backbones/resnext.py, mmseg/models/backbones/swin.py, mmseg/models/backbones/unet.py, mmseg/models/backbones/vit.py, mmseg/models/decode_heads/point_head.py, mmseg/models/decode_heads/sep_fcn_head.py, mmseg/models/necks/fpn.py, mmseg/models/necks/mla_neck.py, mmseg/models/necks/multilevel_neck.py
**Motivation:**
Fix some problems in `readthedocs` (https://mmsegmentation.readthedocs.io/en/latest/), it is caused by wrong docstring usage.
For example, the correct format should be: 
```
""" Encoder-Decoder with Atrous Separable Convolution for Semantic Image Segmentation.
This head is the implementation of `DeepLabV3+ <https://arxiv.org/abs/1802.02611>`_.
Args:
c1_in_channels (int): The input channels of c1 decoder. If is 0,
the no decoder will be used.
c1_channels (int): The intermediate channels of c1 decoder.
"""
```
And in `readthedocs` it would show as below:
=> [Fix] Fix docstring link problem in readthedocs

tools/train.py
As show in 
https://github.com/open-mmlab/mmcv/blob/b4bfeb53c57f2c843cb5015f9c0a2d1689dba9c4/mmcv/runner/base_runner.py#L379 ,
`cfg.gpu_ids` is used to calculate current iteration when resuming checkpoint in `epoch_based_runner` and `based_runner`, but it is `range(1)` in distributed training in default, which will lead to a wrong iteration. Here fix it to `range(world_size)`
=> [Fix] Fix iter bug when resuming checkpoint in distributed train

docker/Dockerfile
Update mmcv installation in dockerfile
`RUN pip install mmcv-full==latest+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html`
-->
`RUN pip install mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA//./}/torch${PYTORCH}/index.html`
No
=> [Fix] Update mmcv installation in dockerfile

mmseg/datasets/custom.py
support load gt for evaluation from multi file backend
=> [Enhancement] Support loading GT for evaluation from multi-file backend

README.md
Just delete redundant lines in README.md
=> [Fix] Fixing README

mmseg/models/segmentors/base.py, tests/test_models/test_segmentors/utils.py
Add loss parse in val_step, so that logger can get loss value of validation dataset
add loss parse and format output dict in val_step function
=> [Fix] Fix loss parse in val_step

mmseg/models/backbones/swin.py, tools/train.py
=> [Fix] Fix load ckpt bug in swin

mmseg/core/seg/sampler/ohem_pixel_sampler.py, mmseg/models/decode_heads/decode_head.py, mmseg/models/decode_heads/point_head.py, tests/test_models/test_heads/test_point_head.py, tests/test_sampler.py
In previous version of MMSegmentation, the `loss_decode` is a dict.
When using multiple losses pipeline, it is changed to `nn.ModuleList()` where each loss would be appended. It would raise BC-Breaking problem.
Thus, we change it back to dict of single loss situation.
=> [Fix] Change `self.loss_decode` back to `dict` in Single Loss situation.

mmseg/models/backbones/mit.py
The latest MMCV(v1.3.17) include a commit open-mmlab/mmcv#1418, which break the compatibility of EfficientMultiheadAttention in MiT.
Change the forward of EfficientMultiheadAttention and add a legacy_forward.
Handle the mmcv version by this:
```python
from mmseg import mmcv_version, digit_version
if mmcv_version < digit_version('1.3.17'):
self.forward = self.legacy_forward
```
Related PR https://github.com/open-mmlab/mmdetection/pull/6488.
No
=> [Fix] Fix EfficientMultiheadAttention in SegFormer

.dev/md2yml.py, configs/unet/unet.yml
In the past, the metric in yml is usually `mIoU`, where some metric such as `Dice` in UNet is wrong.
=> [Fix] Fix Dice Metric in `.yml` file

mmseg/apis/__init__.py, mmseg/apis/train.py, tools/train.py
Currently, when the seed is not set in the command line, the training process will not do anything with seed. This may cause a potential error in some cases (when different threads have different seeds).
- When the seed is not set in the args, it will randomly generate a seed and broadcast to all ranks.
- cfg.seed=seed
Related PR https://github.com/open-mmlab/mmdetection/pull/6354, https://github.com/open-mmlab/mmdetection/pull/6457, https://github.com/open-mmlab/mmdetection/issues/6339
=> [Enchance] Set a random seed when the user does not set a seed

.github/workflows/build.yml, .github/workflows/lint.yml
Signed-off-by: del-zhenwu <dele.zhenwu@gmail.com>
Skip CI workflows for the updates which match the rules
3. If the modification has potential influence on downstream projects, this …
=> Skip CI on ignoring given paths

docs/inference.md, docs_zh-CN/inference.md
Old PR: https://github.com/open-mmlab/mmsegmentation/pull/1092
Motivation: Move Evaluation platform of LoveDA dataset to a new codalab server, where its evaluation speed is faster.
=> [Fix] Change LoveDA codalab server address

mmseg/__init__.py
Related PR: https://github.com/open-mmlab/mmocr/pull/628
MMCV released v1.4.0 lately so the downstream repos should modify their upper version of mmcv.
=> [Fix] Change the upper version of mmcv to 1.5.0

mmseg/models/losses/dice_loss.py
Might be trivial but it may be confusing to someone.
It seems that the `loss_type` arg in `DiceLoss`  is not used anywhere but it exists in the docstring and docs.
=> [Fix] Remove unexist arg in docstring

mmseg/apis/test.py
Fix #1073 
Test error mentioned in #1073 is caused by `pre_eval()` changing the segmentation result.
Changed results from `pre_eval()` from `result` to `pre_eval_results`.
=> [Fix] Fix test error when using --show-dir

mmseg/models/backbones/mit.py, mmseg/models/decode_heads/uper_head.py, mmseg/models/necks/fpn.py, tests/test_models/test_necks/test_fpn.py
Remove the inplace operation in uper_head，which may cause RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation.
Remove the inplace operation in uper_head，which may cause RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation.
=> [Fix] Remove the inplace operation in  uper_head and fpn_neck

mmseg/models/backbones/mit.py, tests/test_models/test_backbones/test_mit.py
[Fix] Fix the bug that mit cannot process init_cfg
[Fix] Fix the bug that mit cannot process init_cfg
=> [Fix] Fix the bug that mit cannot process init_cfg

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml
Cancel the outdated action in `.github/workflows/*.yml` file
modified:   .github/workflows/build.yml
modified:   .github/workflows/deploy.yml
modified:   .github/workflows/lint.yml
[MMCV](https://github.com/open-mmlab/mmcv/pull/1537)
[MIM](https://github.com/open-mmlab/mim/pull/91)
Different repo has different `*.yml` files in `.github/workflows/`.
=> [Fix] Cancel previous runs that are not completed

docs/conf.py, docs_zh-CN/conf.py
Related PR: https://github.com/open-mmlab/mim/pull/89
https://github.com/open-mmlab/mmcv/blob/master/docs/conf.py#L101.
Note: 
(1) MMSegmentation has adopted `pytorch_sphinx_theme` from https://github.com/open-mmlab/mmsegmentation/pull/879.
(2) Currently, some repos do not have Chinese readthe docs, they are `mmhuman3d`, `mmflow` and `mmgeneration`, thus just keep their url. We may change it in the future.
=> [Fix] Unified links of readthedocs in docs

tools/deploy_test.py, tools/print_config.py, tools/test.py, tools/train.py
Revise --option to --options
modified the bug introduced by pr #1129.
In line:
```python
if args.option and args.cfg_opion
```
revise --option to --options
=> [Fix] revise --option to --options

mmseg/datasets/custom.py, mmseg/models/segmentors/base.py
The palette may be different in each iteration if not specified.
Add np.random.seed(42) in [base.py](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/base.py#L212).
Following the method in mmdet.core.visualization.
If this PR introduces a new feature, …
=> [Fix] Set random seed for `palette` if not given.

configs/mobilenet_v3/README.md, configs/mobilenet_v3/mobilenet_v3.yml
Related PR: https://github.com/open-mmlab/mmsegmentation/issues/1191.
Fix paper link of MobileNetV3, the current link is wrong, which is MobileNetV2 paper link.
=> [Fix] Fix mobilenetv3 paper link.

setup.py
Refer to open-mmlab/mmcv#1637 and open-mmlab/mmpose#1135.
=> [Fix] Deprecate the support for "python setup.py test"

.dev/log_collector/example_config.py, .dev/log_collector/log_collector.py, .dev/log_collector/readme.md, .dev/log_collector/utils.py
Add a develop tool: Log Collector
Add a develop tool: Log Collector
=> [Feature] add log collector

mmseg/core/evaluation/class_names.py, tests/test_data/test_dataset.py
Without class names or palette value of `COCOStuffDataset`, community members sometimes may encounter errors when they use COCO-Stuff 10k or COCO-Stuff 164k dataset for visiualization or other operations.
Add palette and class names in [`mmseg/core/evaluation/class_names.py`](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/core/evaluation/class_names.py).
=> [Fix] Add `COCOStuffDataset` in `class_names.py`.

configs/_base_/models/stdc.py, mmseg/models/decode_heads/stdc_head.py
In related Issue: https://github.com/open-mmlab/mmsegmentation/issues/1230. 
It is unnecessary to use `F.interpolate` in `STDCHead` because in `BaseDecodeHead.losses` it already uses `resize( )` in https://github.com/open-mmlab/mmsegmentation/blob/4b905cbe2fb2a8afbb7e91c5453aa5fd8ac6b060/mmseg/models/decode_heads/decode_head.py#L232-L239.
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div style="white-space: pre;" data-zone-id="0" data-line-index="0">
Config names | ss mIoU (old) | ss mIoU (this PR)
-- | -- | --
stdc1_512x1024_80k_cityscapes.py | 71.52 |  71.0
stdc1_in1k-pre_512x1024_80k_cityscapes.py | 75.10 | 75.06 …
=> [Fix] Delete unnecessary lines of STDCHead

tools/train.py
The issue: https://github.com/open-mmlab/mmsegmentation/issues/1261 reports the error.
In `setup_multi_processes`, it uses `get_logger` from MMCV which would initialize new logger if no log initialized. 
If `setup_multi_processes` is used before dump config in `train.py`, it would create two different logs in mmseg.
Solution is simple, just move `setup_multi_processes` behind of `get_logger` part of `train.py`.
=> [Fix] Fix repeating log by `setup_multi_processes`.

.pre-commit-config.yaml, mmseg/datasets/builder.py, setup.cfg, tests/test_config.py, tests/test_metrics.py, tests/test_models/test_losses/test_ce_loss.py, tests/test_models/test_losses/test_dice_loss.py, tests/test_models/test_losses/test_lovasz_loss.py, tools/pytorch2onnx.py
Related PR: https://github.com/open-mmlab/mmflow/pull/87.
1. Remove seed-isort-config in pre-commit hook
2. Upgrade isort to v5.10.1 (latest version)
3. Replace known_standard_library with extra_standard_library
Note: Due to isort upgradation, some .py files would automatically modified by new isort package.
=> [Enhancement] Upgrade isort in pre-commit hook

mmseg/models/backbones/swin.py, mmseg/models/backbones/vit.py
ViT/Swin backbone are using `nn.Module.load_state_dict` to load pre-trained model. This function will return incompatible keys instead of printing them. 
Change to MMCV `load_state_dict` func in ViT/Swin will log out incompatible keys.
No
=> [Improve] Use MMCV load_state_dict func in ViT/Swin

mmseg/models/decode_heads/point_head.py
Support CPU-only usage. User may need to run mmseg on CPU-only. But `mmcv.ops` import will fail on CPU-only installation. Add exception handler to fix that. 
Add an exception for PointRend imports
No
=> [Improve] Add exception for PointRend for support CPU-only usage

mmseg/models/backbones/swin.py
In more and more cases of Transformer models, it may use float `mlp_ratio` such as 0.25 or something else.
It would be simply realized by `int( )`.
=> [Fix] Fix  `mlp_ratio` type in Swin Transformer

mmseg/models/decode_heads/decode_head.py, mmseg/models/decode_heads/point_head.py, mmseg/models/losses/accuracy.py, tests/test_models/test_losses/test_utils.py
Your repository has been so helpful for my projects and I deeply appreciate it. 
My opinion can be wrong, but please look into it and I hope it can be helpful a bit at least.  
I tried to apply 
``` 
reduce_zero_label=True 
``` 
to ignore the background label, and it turned out that the value of acc_seg from the decode_head was weirdly low while other values such as loss and IoU were all looking good. Looking into the decode_head.py, 
```python
@force_fp32(apply_to=('seg_logit', ))
def losses(self, seg_logit, seg_label):
"""Compute segmentation loss."""
loss = dict()
seg_logit = resize(
input=seg_logit,
size=seg_label.shape[2:],
mode='bilinear',
align_corners=self.align_corners)
if self.sampler is not None:
seg_weight = self.sampler.sample(seg_logit, seg_label)
else:
seg_weight = None …
```
=> [Fix] Make accuracy take into account ignore_index 

docs/en/get_started.md
the image file name should be demo.png instead of demo.jpg.
=> wrong image format name in the demo

tests/test_models/test_backbones/test_blocks.py
In latest MMCV==1.4.5, it uses PyTorch official implementation of HardSwish when Pytorch > 1.6.
Related PR: https://github.com/open-mmlab/mmcv/pull/1709.
We would add more flexible assertion in MMSegmentation unit test to pass CI.
=> [Fix] Add Pytorch HardSwish assertion in unit test

mmseg/core/evaluation/class_names.py, mmseg/datasets/isprs.py
In original vaihingen dataset pr: https://github.com/open-mmlab/mmsegmentation/pull/1171.
The value of palette is wrong, which should be the same like [Potsdam](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/potsdam.py#L17-L18) because those two datasets have same class names.
=> [Fix] Fix wrong palette value in vaihingen

configs/setr/README.md, configs/setr/setr_mla_512x512_160k_b8_ade20k.py, configs/setr/setr_naive_512x512_160k_b16_ade20k.py, configs/setr/setr_pup_512x512_160k_b16_ade20k.py, configs/setr/setr_vit-large_mla_8x1_768x768_80k_cityscapes.py, configs/setr/setr_vit-large_naive_8x1_768x768_80k_cityscapes.py, configs/setr/setr_vit-large_pup_8x1_768x768_80k_cityscapes.py
Fix #1288  the bug that setr cannot load pretrain
Fix the bug that setr cannot load pretrain
=> [Fix] Fix the bug that setr cannot load pretrain

docs/en/dataset_prepare.md
Fix iSAID dataset conversion default setting in doc.
Related PR: https://github.com/open-mmlab/mmsegmentation/pull/1115.
The default setting could be found here:https://github.com/open-mmlab/mmsegmentation/blob/master/tools/convert_datasets/isaid.py.
The chinese doc is correct: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/dataset_prepare.md#isaid.
Default setting is: `patch_width`=896, `patch_height`=896,　`overlap_area`=384.
=> [Fix] Fix iSAID dataset conversion default setting in doc.

README.md, README_zh-CN.md
=> [Doc] add MMRotate link

.github/workflows/build.yml, requirements/runtime.txt, requirements/tests.txt
Add win-ci in .github/workflows/build.yml
ref pr: https://github.com/open-mmlab/mmediting/pull/732, https://github.com/open-mmlab/mmflow/pull/92.
=> [Enhancement] Add win-ci

.pre-commit-config.yaml, demo/video_demo.py, mmseg/datasets/coco_stuff.py, mmseg/datasets/dark_zurich.py, mmseg/datasets/isaid.py, mmseg/datasets/night_driving.py, mmseg/models/backbones/icnet.py, mmseg/models/backbones/twins.py, mmseg/models/decode_heads/dpt_head.py, mmseg/models/decode_heads/isa_head.py, mmseg/models/necks/ic_neck.py, mmseg/models/utils/__init__.py, tests/test_apis/test_single_gpu.py, tests/test_models/test_backbones/test_swin.py, tests/test_models/test_backbones/test_twins.py, tests/test_models/test_heads/test_dpt_head.py, tests/test_models/test_utils/__init__.py, tools/browse_dataset.py, tools/convert_datasets/coco_stuff10k.py, tools/convert_datasets/coco_stuff164k.py, tools/convert_datasets/isaid.py, tools/model_converters/vitjax2mmseg.py, tools/torchserve/test_torchserve.py
Add `check-algo-redame` and `check-copyright` hooks  ref:  https://github.com/open-mmlab/mmdeploy/pull/166
- modify pre-commit hook yml
- Add copyrights on files
1. …
=> [Enhancement] Revise pre-commit-hooks

mmseg/models/decode_heads/dnl_head.py
fix export onnx inference difference type Cast error.
When use this class in model, if export to onnx, and use onnx runtime inference, It will case the Cast difference format error.
and the orginal onnx graph is:
- first Cast output is Float, but the `Pow` need Float64.
-  second Cast output is Int64, but the `Div` Op is need Float64
After modify the code used in this PR, the output onnx graph is 
4. The documentation has been modified accordingly, like …
=> fix dnl_head export onnx inference difference type Cast error

mmseg/datasets/pipelines/transforms.py, tests/test_data/test_transform.py
add setr_resize
add setr_resize
=> [Feature] Add `min_size` arg in `Resize` to keep the shape after resize bigger than slide window

docs/en/useful_tools.md, tools/confusion_matrix.py
Thank you for the great repository. I've been inspired a lot by you guys! 
Here is the PR that adds a python file to generate/plot a normalized confusion matrix (n_classes x n_classes). The most part of the file is from [mmdetection repo.](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/confusion_matrix.py), and I changed it a bit in a way to be able to work on segmentation tasks. I tested it on my local computer with some prediction results formatted in .pkl. The plot looks like this!
If you get interested, I will add UT for this feature! 
There was neither a function to generate n_classes x n_classes confusion matrix nor to draw it. (related Issue: https://github.com/open-mmlab/mmsegmentation/issues/1203). I thought it's always better to visualize everything, …
=> [Feature] Generating and plotting confusion matrix 

README.md, README_zh-CN.md, configs/convnext/README.md
ConvNeXt has been accepted by CVPR'2022. 6 hours ago official repo has also modified its journal info.
https://github.com/facebookresearch/ConvNeXt/commit/6e08219f9e4c527443d2e44643a9dba79d995b07
=> [Docs] Change ConvNeXt journal infomation

configs/_base_/models/segmenter_vit-b16_mask.py, configs/_base_/models/twins_pcpvt-s_fpn.py, configs/_base_/models/twins_pcpvt-s_upernet.py, configs/segmenter/README.md, configs/segmenter/segmenter_vit-l_mask_8x1_512x512_160k_ade20k.py, configs/segmenter/segmenter_vit-s_mask_8x1_512x512_160k_ade20k.py, configs/segmenter/segmenter_vit-t_mask_8x1_512x512_160k_ade20k.py, configs/stdc/README.md, configs/stdc/stdc1_in1k-pre_512x1024_80k_cityscapes.py, configs/stdc/stdc2_in1k-pre_512x1024_80k_cityscapes.py, configs/twins/README.md, configs/twins/twins_pcpvt-b_fpn_fpnhead_8x4_512x512_80k_ade20k.py, configs/twins/twins_pcpvt-b_uperhead_8x2_512x512_160k_ade20k.py, configs/twins/twins_pcpvt-l_fpn_fpnhead_8x4_512x512_80k_ade20k.py, configs/twins/twins_pcpvt-l_uperhead_8x2_512x512_160k_ade20k.py, configs/twins/twins_svt-b_fpn_fpnhead_8x4_512x512_80k_ade20k.py, configs/twins/twins_svt-b_uperhead_8x2_512x512_160k_ade20k.py, configs/twins/twins_svt-l_fpn_fpnhead_8x4_512x512_80k_ade20k.py, configs/twins/twins_svt-l_uperhead_8x2_512x512_160k_ade20k.py, configs/twins/twins_svt-s_fpn_fpnhead_8x4_512x512_80k_ade20k.py, configs/twins/twins_svt-s_uperhead_8x2_512x512_160k_ade20k.py
To replace `./pretrain/xxx.pth` in configs of twins, segmenter and stdc with URL of MMSegmentation style pretrained models.
In this way, users of MMSegmentation could directly use these config files to train.
=> [Feature] Provide URLs of STDC, Segmenter and Twins pretrained models

docs/en/tutorials/config.md
=> [Doc] Update config.md

demo/MMSegmentation_Tutorial.ipynb
=> [Fix] Typo in MMSegmentation_Tutorial.ipynb

mmseg/models/utils/__init__.py, mmseg/models/utils/shape_convert.py, tests/test_models/test_utils/test_shape_convert.py
add nlc2nchw2nlc and nchw2nlc2nchw. These 2 functions can make the code of models more compact and easier to write.
add nlc2nchw2nlc and nchw2nlc2nchw
=> [Feature] add nlc2nchw2nlc and nchw2nlc2nchw

mmseg/core/evaluation/class_names.py
Add STARE dataset demo/image_demo.py support
`mmseg/core/evaluation/class_names.py`
```python
def stare_classes():
"""stare class names for external use."""
return ['background', 'vessel']
def stare_palette():
"""STARE palette for external use"""
return [[120, 120, 120], [6, 230, 230]]
````
=> Support #1375: add demo/image_demo.py support for STARE

docs/en/train.md, docs/zh_cn/train.md, mmseg/core/evaluation/class_names.py, tools/dist_test.sh, tools/dist_train.sh
Add more detailed documentation for users of single and multi-machine training to suit different development environments.
ref: https://github.com/open-mmlab/mmselfsup/pull/232
Add the English and Chinese description documents of startup tasks. Modify the tools/dist_train.sh and tools/dist_test.sh files.
=> [Feature] Add multi machine `dist_train`.

tools/confusion_matrix.py
There are some arguments of tools/confusion_matrix.py is not effective, and this pull request aims to fix that.
Fixing the arguments passing for the plot function.
NA
=> [Fix] make arguments effective in tools/confusion_matrix.py

demo/MMSegmentation_Tutorial.ipynb, mmseg/core/evaluation/class_names.py
Fixed outdated link in colab notebook for how to customize your datasets by reorganizing data.
=> colab notebook: fix outdated link for doc

mmseg/models/necks/fpn.py
=> [Fix] Fix typo in FPN neck

docs/zh_cn/train.md
There is a typo in `docs/zh_cn/train.md` .
`docs/zh_cn/train.md`  
Line #16 modify `ith` -> `with`
=> fix word spelling mistake

mmseg/datasets/chase_db1.py, mmseg/datasets/custom.py, mmseg/datasets/drive.py, mmseg/datasets/hrf.py, mmseg/datasets/isaid.py, mmseg/datasets/pascal_context.py
Support to initialize dataset from file_client
1. Add `file_client_args` in `__init__` with default value `dict(backend='disk')`
2. scan directory  with `file_client.list_dir_or_file` in `load_annotations`
3. Read split file with `mmcv.list_from_file` in `load_annotations`
```
file_client_args = dict(
backend='petrel',
path_mapping=dict({
'.data/cityscapes/': 'openmmlab:s3://openmmlab/datasets/segmentation/cityscapes/',
'data/cityscapes/': 'openmmlab:s3://openmmlab/datasets/segmentation/cityscapes/'
}))
data = dict(
... …
```
=> [Feature] Support dataset initialization with file_client

docs/en/tutorials/training_tricks.md, docs/zh_cn/tutorials/training_tricks.md, mmseg/models/decode_heads/decode_head.py, mmseg/models/losses/cross_entropy_loss.py, mmseg/models/losses/utils.py, tests/test_models/test_losses/test_ce_loss.py
Right now, MMSegmentation do not support `ignore_index` in loss average over non-ignored elements in CE loss.
fix https://github.com/open-mmlab/mmsegmentation/pull/578.
old pr: https://github.com/open-mmlab/mmsegmentation/pull/1388.
In old PR: https://github.com/open-mmlab/mmsegmentation/pull/578, the author fixed it while it left a bug if all labels in one image is `ignore_index`, `avg_factor` would be zero and ZeroDivisionError would be rasied in `weight_reduce_loss` function.
Just take [fcn_unet_s5-d16_128x128_40k_chase_db1.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/unet/fcn_unet_s5-d16_128x128_40k_chase_db1.py), its [base config](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/fcn_unet_s5-d16.py) for example:
original config: …
=> [Fix] Add avg_non_ignore in cross entropy loss

tools/analyze_logs.py
Fix https://github.com/open-mmlab/mmsegmentation/issues/1426
Current in `tools/analyse_logs.py` we assert whether certain line in `log.json` is validation rather than training set by:
```python
if pre_iter > epoch_logs['iter'][idx]:
continue
```
It's OK in many cases like below ` 32000 (pre_iter) > 250 (epoch_logs['iter'][idx]) `.
It is in ConvNeXt, whose validation step is 16000. Of course, 16000, 32000, 48000 and so on those values > 250. 
Note that 250 is related with number of images in validation sets.
However, in certain cases when (1) valitaion is large and (2) validation step is small, like below:
The valition has 1334 images and validation step is 200. So  ` 200 (pre_iter) < 1334 (epoch_logs['iter'][idx]) `. And it would generate many `1334` in `plot_iters` which makes a …
=> [Fix] Fix bug in `tools/analyse_logs.py` caused by wrong plot_iter in some cases.

mmseg/apis/train.py
- Add `DistSamplerSeedHook` to set epoch num to dataloader when runner is  `EpochBasedRunner`
- register `DistSamplerSeedHook` hook in apis/train.py
1. Pre-commit or other …
=> Add DistSamplerSeedHook for when runner is EpochBasedRunner

mmseg/datasets/pipelines/loading.py
When I use label_map to change train_label, I found that when the label map is complex, the current code is likely to repeatedly replace gt_semantic_seg. 
For example, when my label_map is dict{6:9, 9:7}, the intention is to replace 6 with 9 and 9 with 7, but the result does replace 6 with 7. 
Record the initial gt_semantic_seg with a copy!
=> fix bug about label_map

tools/convert_datasets/isaid.py
when run `.\tools\convert_datasets\isaid.py`  in Windows OS,  as the path str has no `/`，there will get wrong image save path.
using `os.path.basename(src_path).split('.')[0]` to get the filename without suffix.
=> [fix] fix image save path bug in Windows

mmseg/models/decode_heads/stdc_head.py
fix #1462
- revise `seg_label.float`  to `seg_label.to(self.laplacian_kernel)` in mmseg/models/decode_heads/stdc_head.py
1. Pre-commit or other linting tools are used to fix …
=> [Fix] inconsistent dtype of `seg_label` in stdc decode

mmseg/datasets/custom.py
`seg_map` or `gt_seg_maps` are already converted by the `label_map` during `self.get_gt_seg_map_by_idx` or `self.get_gt_seg_maps`, pass the `self.label_map` to `intersect_and_union` or `eval_metrics` will do the conversion again.
https://github.com/open-mmlab/mmsegmentation/issues/1415
=> Avoid converting label ids twice by label map during evaluation

mmseg/apis/train.py, tools/test.py
ref: https://github.com/open-mmlab/mmclassification/pull/752
In some situation, we need to use different dataloader settings like samples_per_gpu in train/val/test dataloader.
Use train_dataloader, val_dataloader and test_dataloader settings in the data field to specify different arguments.
```python
data = dict(
samples_per_gpu=64,
workers_per_gpu=4,
train=dict(type='xxx', ...),
val=dict(type='xxx', ...),
test=dict(type='xxx', ...),
val_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2), …
```
=> [Enhance] Add extra dataloader settings in configs

mmseg/models/segmentors/cascade_encoder_decoder.py
fix # https://github.com/open-mmlab/mmsegmentation/issues/1353
- Input `prev_outputs` to `forward_test` for the latter `cascade_decode_head`.
1. Pre-commit or other linting …
=> [Fix] Input previous results for the last cascade_decode_head

mmseg/models/losses/cross_entropy_loss.py, tests/test_models/test_losses/test_ce_loss.py
Fix the bug that binary cross entropy loss doesn't support single channel input.
Related Issue: https://github.com/open-mmlab/mmsegmentation/issues/1430
1. When the channel of `pred` is one, instead of expanding the lebel to one-hot format, `binary_cross_entropy_loss` only unsqueeze the `label` to match the shape of the `pred`.
2. Add a new test function to cover the new codes.
=> [Fix] Support single cahnnel `pred` for Binary Cross Entropy Loss

mmseg/models/losses/accuracy.py
There is a potential bug in accuracy.py, and This PR aims to fix this issue. 
In line https://github.com/open-mmlab/mmsegmentation/blob/618d3c3bccdceb45372fb2e9e9228285af63fe4d/mmseg/models/losses/accuracy.py#L48, `correct = correct[:, target != ignore_index]` is used to filter out the ignored targets. However, as the default value of `ignore_index` is None, this line would cause unwanted behavior. For example
```python
>>> target = torch.ones(3)
>>> target != 255
tensor([True,  True, True])
>>> target != None
True
>>> …
```
=> Fix potential bugs in accuracy.py

demo/MMSegmentation_Tutorial.ipynb
i fixed a couple of issues that made the notebook not work in colab 
1. it downloaded incompatible versions of pytorch and cuda + the conda command doesnt do anything in colab since there is no conda in colab idk w y wanna do about that - The commit of 2 days ago only changes the conda command version and not the pip command which is used while isntaling mcvv
2. /demo.png doesnt exist in colab so i added a wget to download some cityscapes photo from the internet and run inference on that photo
3. i think it would be optimal to have 2 notebooks. 1 for running locally when cloning your git branch and one to run in google colab.
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do …
=>  fixed a couple of issues that made the notebook not work in colab

mmseg/models/segmentors/base.py
The validation loss is currently not logged in the setting of both train and val workflow modes.
The problem is described in this issue:
https://github.com/open-mmlab/mmsegmentation/issues/1396
> Iteration runner calls the model's val_step here
https://github.com/open-mmlab/mmcv/blob/44edcdd91f8940a58c9680c609febc757a50a040/mmcv/runner/iter_based_runner.py#L77
> The model's val_step returns the loss under the same key as in the training mode, which gets lost in all output logs later on.
```
2022-04-19 19:32:16,444 - mmseg - INFO - workflow: [('train', 1), ('val', 1)], max: 60000 iters
2022-04-19 19:32:16,444 - mmseg - INFO - Checkpoints will be saved to /home/SENSETIME/zhengmiao/openmmlab/mmsegmentation/work_dir/test_val by HardDiskBackend.
2022-04-19 19:32:28,897 - mmseg - INFO - Iter …
```
=> Fix validation loss logging

configs/beit/README.md
We are going to use a new blob account to store the checkpoints.
Modify the azure blob storage URLs for BEiT checkpoints.
It does not break the compatibility.
=> migrate azure blob for beit checkpoints

mmseg/models/backbones/beit.py, mmseg/models/backbones/vit.py
1. Remove redundant code
2. Modularize attention and transformer encode layer
1. Add build function for attn and ffn in `TransformerEncoderLayer`
2. Add `attn_cfg` and `ffn_cfg` in `TransformerEncoderLayer`
3. Revise `qk_bias` to `bias` in `BEiTAttention`
| Method | before refactor  | inference test after refactor| training result after refactor
| ------ | ------------------ |------------------ |------------------ |
| upernet_beit-base_8x2_640x640_160k_ade20k | 53.08 | 53.08 | 52.85|
| upernet_vit-b16_mln_512x512_160k_ade20k | …
=> [Refactor] Refactor transfomer encode layer in ViT and BEiT backbone

configs/bisenetv1/bisenetv1_r18-d32_in1k-pre_4x8_1024x1024_160k_cityscapes.py, configs/bisenetv2/bisenetv2_fcn_4x8_1024x1024_160k_cityscapes.py, configs/cgnet/cgnet_512x1024_60k_cityscapes.py, configs/cgnet/cgnet_680x680_60k_cityscapes.py
When workers of dataloader are too many, it might affect CPU efficiency and speed.
1. revise`workers_per_gpu=8` to ` workers_per_gpu=4`
=> [Fix] Revise high workers_per_gpus

tools/dist_train.sh
dist_train will not set seed = 0 and dist_train should be aligned with slurm_train.
1. Remove `seed` in `dist_trian`
1. Pre-commit or other linting tools are used to fix the …
=> [Enhancement] Delete seed in dist_train.sh

.github/workflows/build.yml
CI Installation is broken.
related pr https://github.com/open-mmlab/mmocr/pull/988
Add libgl1-mesa-glx in system dependencies
1. Pre-commit or other linting tools are used to …
=> [Fix] Add GPG keys  in CI

mmseg/core/optimizers/layer_decay_optimizer_constructor.py
MAE need LayerDecayOptimizerConstructor
Add MAE in mmseg/core/optimizers/layer_decay_optimizer_constructor.py
=> [Fix] Add MAE LayerDecayOptimizerConstructor

configs/segmenter/README.md
Replace Arxiv with ICCV bibtex entry
Source: https://openaccess.thecvf.com/content/ICCV2021/html/Strudel_Segmenter_Transformer_for_Semantic_Segmentation_ICCV_2021_paper.html
=> Replace Arxiv with ICCV bibtex entry

configs/mae/README.md
The main line link in MAE readme misses one character "L".
From 
```python
<a href="https://github.com/open-mmlab/mmsegmentation/blob/v0.24.0/mmseg/models/backbones/mae.py#46">Code Snippet</a>
```
to
```python
<a href="https://github.com/open-mmlab/mmsegmentation/blob/v0.24.0/mmseg/models/backbones/mae.py#L46">Code Snippet</a>
```
=> [Fix] Fix main line link in MAE README.md

docker/Dockerfile
resolved https://github.com/open-mmlab/mmsegmentation/issues/1567
Dockerfile changed to install `libgl1-mesa-dev` for demo script.
Related PR in MMOCR: https://github.com/open-mmlab/mmocr/pull/109.
=> fixed Dockerfile to run demo script in docker container

.dev/md2yml.py
Currently, `md2yml.py` is usually used in MMSegmentation for generating metafile of each algorithm automatically.
However,  `UnicodeDecodeError` would be raised if not specified encoding format of each markdown file.
Error above would be solved only needs to add `encoding='UTF-8'`:
=> [Fix] Fix `UnicodeDecodeError` in `md2yml.py`

docs/en/get_started.md, docs/zh_cn/get_started.md
I try to see the demo jupyter notebook` inference_demo.ipynb`, but the superlink in `get_started.md` is wrong
Correct the `inference_demo.ipynb` superlink in get_started.md
=> fix: correct inference_demo.ipynb path

.github/workflows/build.yml
1. CI failed when testing windows platform, it needs fixing the pip up-grading command
1. Revise .github/workflows/build.yml
None
=> [Fix] pip up grade when testing windows platform

mmseg/models/losses/cross_entropy_loss.py
The motivation of this PR is to fix the error of `binary_cross_entropy` when the batch size is 1.
- binary_cross_entropy  
Modify the `pred.squeeze()` to `pred.squeeze(1)` to avoid the error caused by squeeze dimension 0 when batch size is 1.
No
=> [Fix] Fix the error of BCE loss when batch size is 1.

docs/en/faq.md, docs/en/get_started.md
Reorganize the installation guide
Refer to open-mmlab/mmdetection#7897
=> [Doc] Rewrite the installation guide

README.md, README_zh-CN.md
- add quick links
- modify the alignment of Badges to `center`
- move `License` below `Citation`
=> [Doc] Format readme

mmseg/models/backbones/vit.py
Operations on weight is not good for tracing and exporting to ONNX.
Use slice to keep dim in `mmseg/models/backbones/vit.py`
None
=> Slice and keep dim for easy deployment of vit

.github/workflows/test_mim.yml
Test search command of mim in CI to ensure the format of metafile is correct.
Add .github/workflows/test_mim.yml
No
4. The documentation has been modified accordingly, like docstring or example …
=> Test commands of mim in CI

mmseg/datasets/pipelines/test_time_aug.py, mmseg/models/segmentors/encoder_decoder.py, tests/test_data/test_tta.py
- Before padding
-  After padding
I use mmseg to train my model and found the mask has a left offset to the image. Finally I found that it is caused by inference input without padding. For example, A input with origin shape (1920, 1080) and `img_scale=(2048, 512)` will be resized to `(910 , 512)`.   When infer it with resnet50-d8，the final feature map is 114 * 64 and then resize it to 910*512. Attention that 114x8=912. So it is same with pad the input to (912, 512) and resize feature to (910, 512). With 2-pixel left offset
Attention that when `dict(type='Pad', size_divisor=32),` is add, the model performance will intend to be improved, I have test several mIoU rise
- `configs/deeplabv3plus/deeplabv3plus_r50-d8_512x512_80k_ade20k.py`
from 42.72 to 42.78
- …
=> [Enchance] support infererence with padding

LICENSES.md
Because of my carelessness, those `features` are wrongly replaced by `operations`. Now they are all modified.
Sorry for my carelessness.
=> [Fix] Fix typo in LINCENSES.md

configs/segformer/README.md
Add notation in README that we adopt default training pipeline in MMSegmentation while SegFormer original repo uses `RepeatDataset` for training acceleration.
=> [Fix] Add notation of training setting of SegFormer

mmseg/core/hook/wandblogger_hook.py
#1740 
Remove unnecessary `show=False` argument in test_fn
=> [Fix] Remove `show=False` argument in WandbHook

docs/zh_cn/get_started.md
Fix a typo in zh_CN documentation.
Changes `从而无需重新安# 装` -> `从而无需重新安装`.
=> [Fix] Fix a typo in get_started.md

demo/MMSegmentation_Tutorial.ipynb
#1763 
- Install PyTorch through `pip`
- Install mmcv-full through `mim`
- Use mmseg.utils.get_device() method to set cfg.device
=> [Fix] Fix colab mmcv installation

docs/en/tutorials/customize_datasets.md
'batch_size' calculate error. 
batch_size is 8 * 4=16 ==> batch_size is 8 * 4=32
=> [Fix] Fix batch_size description error. 

mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/loading.py, tests/test_datasets/test_loading.py
Can be used when loading images from the webcam.
- add LoadImageFromNDArray class
- add unit test
Ref: https://github.com/open-mmlab/mmdetection/blob/a0a0211217edf66cd66b8e4074e45cc0f3dafbf7/mmdet/datasets/transforms/loading.py#L16
=> [Feature] Add LoadImageFromNdArray pipeline

demo/MMSegmentation_Tutorial.ipynb, mmseg/datasets/__init__.py, mmseg/datasets/ade.py, mmseg/datasets/chase_db1.py, mmseg/datasets/cityscapes.py, mmseg/datasets/coco_stuff.py, mmseg/datasets/custom.py, mmseg/datasets/drive.py, mmseg/datasets/hrf.py, mmseg/datasets/isaid.py, mmseg/datasets/isprs.py, mmseg/datasets/loveda.py, mmseg/datasets/pascal_context.py, mmseg/datasets/potsdam.py, mmseg/datasets/stare.py, mmseg/datasets/voc.py, tests/test_datasets/test_dataset.py, tests/test_datasets/test_dataset_builder.py
Change `CustomDataset` to `BaseSegDataset`.
=> [Fix] Change CustomDataset to BaseSegDataset

tests/test_datasets/test_dataset.py
Fix bug produced by https://github.com/open-mmlab/mmsegmentation/pull/1791
Just add 
```python
from mmseg.registry import DATASETS
```
=> [Fix] Fix DATASETS not imported error

mmseg/models/backbones/beit.py, mmseg/models/backbones/bisenetv1.py, mmseg/models/backbones/bisenetv2.py, mmseg/models/backbones/cgnet.py, mmseg/models/backbones/erfnet.py, mmseg/models/backbones/fast_scnn.py, mmseg/models/backbones/hrnet.py, mmseg/models/backbones/icnet.py, mmseg/models/backbones/mit.py, mmseg/models/backbones/mobilenet_v2.py, mmseg/models/backbones/mobilenet_v3.py, mmseg/models/backbones/resnet.py, mmseg/models/backbones/timm_backbone.py, mmseg/models/backbones/twins.py, mmseg/models/backbones/unet.py, mmseg/models/decode_heads/decode_head.py, mmseg/models/decode_heads/dpt_head.py, mmseg/models/necks/fpn.py, mmseg/models/necks/ic_neck.py, mmseg/models/necks/jpu.py
Import `BaseModule` from MMEngine rather than MMCV.
=> [Fix] Use MMEngine BaseModule

docs/en/tutorials/customize_models.md, docs/zh_cn/tutorials/customize_models.md
find a typo in  customize_models.md 
Fix a typo in documentation.
```python
=====
- from ..registry import BACKBONES
+ from ..builder import BACKBONES
=====
```
=> [Fix] Fix typo in customize_models.md

tests/test_visualization/test_local_visualizer.py
1. Make ut of `SegLocalVisualizer` more robust.
1. tests/test_visualization/test_local_visualizer.py
=> [Fix] Fix SegLocalVisualizer UT

configs/_base_/schedules/schedule_160k.py, configs/_base_/schedules/schedule_20k.py, configs/_base_/schedules/schedule_320k.py, configs/_base_/schedules/schedule_40k.py, configs/_base_/schedules/schedule_80k.py
The step of each eval record in the json log is 0
Modify the parameter of `LoggerHook`.
```python
default_hooks = dict(
...,
logger=dict(type='LoggerHook', interval=50, log_metric_by_epoch=False),
...
```
=> [Fix] Fix LoggerHook cfg

mmseg/engine/hooks/visualization_hook.py, tests/test_engine/test_visualization_hook.py
1. `Hook` call `after_val_iter`  and `after_test_iter` by `_after_iter`
```python
def after_val_iter(self,
runner,
batch_idx: int,
data_batch: DATA_BATCH = None,
outputs: Optional[Sequence[BaseDataElement]] = None) -> None:
self._after_iter(
runner,
batch_idx=batch_idx,
data_batch=data_batch,
outputs=outputs,
mode='val')
```
1. `after_iter` -> `_after_iter`
If so, please describe how it breaks the compatibility and how the …
=> [Fix] Fix after iter `SegVisualizationHook`

mmseg/models/losses/__init__.py, mmseg/models/losses/tversky_loss.py, tests/test_models/test_losses/test_tversky_loss.py
Adding new loss function named `Tversky Loss`. https://arxiv.org/abs/1706.05721
Old PR: https://github.com/open-mmlab/mmsegmentation/pull/634, https://github.com/open-mmlab/mmsegmentation/pull/919
|    Datasets    | loss_ce (from [repo config](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/unet)) | loss_ce + loss_tversky (1:1) | loss_ce + loss_tversky (1:3) | loss_tversky |
| ---------- | --- | --- | --- | --- |
| DRIVE |  <u> 78.67 </u> | 79.39 | 79.81 | 79.72 |
| STARE       |  81.02 | 82.3 | 82.62 | 82.03 |
| CHASE_DB1       |  80.24 | 80.37 | 79.74 | 77.95 |
| HRF       |  79.45 | 81.03 | -- | -- |
=> [Feature] Support Tversky Loss

mmseg/models/decode_heads/decode_head.py
The motivation of this PR is to change the `self.forward(inputs)` to `self(inputs)` to solve the problem of not being able to call the pytorch hook.
- BaseDecodeHead
Replace the `self.forward(inputs)` with `self(inputs)`.
NO.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
=> [Fix] Fix decode head forward_train error.

tests/test_utils/test_util_distribution.py
=> [Fix] Fix ddp ut

.dev/benchmark_inference.py, .dev/check_urls.py, .dev/gather_benchmark_evaluation_results.py, .dev/gather_benchmark_train_results.py, .dev/gather_models.py, .dev/generate_benchmark_evaluation_script.py, .dev/generate_benchmark_train_script.py, .dev/log_collector/log_collector.py, .dev/upload_modelzoo.py, docs/en/tutorials/config.md, docs/zh_cn/tutorials/config.md, setup.py
I started to read code details in MMSeg project for going to deep to project. Then I refactored some code part to better syntax
I changed my latest commit in docs to explain details. Then I modified .dev directory Pythons file and setup.py.
=> [Enhancement] .dev Python files updated to get better performance and syntax

tools/train.py
`resume` is only used to specify whether launch resume training from the latest checkpoint and `load-from` is used to load specific checkpoints.
`resume` in CLI has the same function of `resume` in `Runner`. https://github.com/open-mmlab/mmengine/blob/ca0364bbc3a6ac9132f5d499de190f7e733383ca/mmengine/runner/runner.py#L151-L154
1. Add action of `resume`.
2. Remove the load ckpt from `resume`.
If so, please describe how it breaks …
=> [Refactor]Resume do not specify ckpt

mmseg/core/evaluation/metrics.py
According to https://github.com/open-mmlab/mmsegmentation/pull/1445, evaluation part should be changed, too.
Record the initial label with `.clone()`, because `label` is `torch.tensor`.
=> fix bug about label_map in evaluation part

docs/en/user_guides/4_train_test.md
As title.
Update the structure:
- Tutorial 4: Train and test with existing models
- Training and testing on a single machine with a single GPU
- Training on a single GPU
- Testing on a single GPU
- Training and testing on multiple GPUs and multiple machines
- Training on multiple GPUs
- Testing oh multiple GPUs
- Launch multiple jobs on a single machine
- Train with multiple machines
- Manage jobs with Slurm
- Training on a cluster with Slurm
- Testing on a cluster with Slurm
=> [Doc] Update train test doc

mmseg/apis/inference.py, mmseg/visualization/local_visualizer.py, tests/test_visualization/test_local_visualizer.py
1. mmseg/apis/inference.py
2. mmseg/visualization/local_visualizer.py
=> [Enhancement]Add `out_file` in add_datasample to directly save image

mmseg/models/decode_heads/decode_head.py, mmseg/models/segmentors/base.py, mmseg/models/segmentors/encoder_decoder.py, tests/test_models/test_heads/test_decode_head.py, tests/test_models/test_segmentors/__init__.py, tests/test_models/test_segmentors/test_cascade_encoder_decoder.py, tests/test_models/test_segmentors/test_encoder_decoder.py, tests/test_models/test_segmentors/utils.py
As #2016 
1. Add threshold and out_channels parameters to `decode_head`
2. Fix inference logits while `num_classes==1`
=> [Fix] Fix binary segmentation

docs/en/advanced_guides/add_models.md
As title.
- fix type
- remove customize optimizer and customize optimizer constructor
- add develop new segmentor
=> [Doc] Update add module doc

.github/workflows/build.yml, .pre-commit-config.yaml, docs/en/faq.md, docs/en/tutorials/customize_datasets.md, mmseg/models/backbones/vit.py, mmseg/models/losses/focal_loss.py, setup.cfg
related pr https://github.com/open-mmlab/mmengine/pull/576
=> Upgrade pre commit hooks master

mmseg/models/decode_heads/fcn_head.py
The first conv in the previous implementation is unnecessary since the input channels can be determined when passing parameters.
The first conv is combined into the loops. Thus, the readability and structure are improved..
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
=> Improve structure and readability for FCNHead

docker/serve/Dockerfile
While building the torchserve docker container, I noticed some errors due to missing dependencies.
I added the Nvidia APT keys to the container before installing packages. I also added nvgpu pip dependency as it was required later on by the server to retrieve GPU usage stats. The container image is now built without errors.
=> Add missing dependencies to torchserve docker file

.circleci/test.yml, .github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
=> [Fix] Ignore test timm when torch<1.7

configs/segformer/README.md, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Fix ResizeToMultiple transform in MMSeg 1.x.
In current  `ResizeToMultiple`, it has:
```python
results['img'] = img
results['img_shape'] = img.shape
results['pad_shape'] = img.shape
```
If `dict(type='ResizeToMultiple', size_divisor=32),` is added, because in https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/mmseg/models/utils/wrappers.py#L27, the `input` and  `size` should have same dimension, but currently it is 2 and 3, respectively. And it would cause error `ValueError: size shape must match input shape. Input is 2D, size is 3`:
Just modify `ResizeToMultiple`:
```python
results['img'] = img
results['img_shape'] = img.shape[:2]
results['pad_shape'] = img.shape[:2]
```
=> [Fix] Fix ResizeToMultiple transform in MMSeg 1.x

README.md, README_zh-CN.md, configs/_base_/models/fpn_poolformer_s12.py, configs/poolformer/README.md, configs/poolformer/fpn_poolformer_m36_8xb4-40k_ade20k-512x512.py, configs/poolformer/fpn_poolformer_m48_8xb4-40k_ade20k-512x512.py, configs/poolformer/fpn_poolformer_s12_8xb4-40k_ade20k-512x512.py, configs/poolformer/fpn_poolformer_s24_8xb4-40k_ade20k-512x512.py, configs/poolformer/fpn_poolformer_s36_8x4_512x512_40k_ade20k.py, configs/poolformer/poolformer.yml, model-index.yml, tests/test_config.py
Support PoolFormer in MMSeg 1.x branch.
0.x PR: https://github.com/open-mmlab/mmsegmentation/pull/1537
Fix mIoU results without `ResizeToMultiple` transforms in test pipeline of master branch, which are lower than their real results.
Related PR: https://github.com/open-mmlab/mmsegmentation/pull/2190
Here are five re-implementation results using MMSegmentation dev-1.x branch:
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div style="white-space: pre;" data-zone-id="0" data-line-index="0">
  | mIoU | mIoU\* | MMSEG dev-1.x re-implementation 5 times mIoU\*
-- | -- | -- | --
PoolFormer-S12 | 36.68 | 37.07 | 36.95, 36.62, 36.37, …
=> [Feature] Support PoolFormer in MMSegmentation 2.0

docs/en/faq.md, docs/zh_cn/faq.md, mmseg/models/decode_heads/decode_head.py
Update FAQ doc about  binary segmentation problem and `reduce_zero_label` usage.
=> [Doc] Update FAQ doc about binary segmentation and ReduceZeroLabel

docs/en/tutorials/customize_datasets.md
This PR is for fixing typo in `docs/en/tutorials/customize_datasets.md`.
Fix typo.
=> Fix typo in `docs/en/tutorials/customize_datasets.md`.

mmseg/models/backbones/swin.py
Fix the problem that state_dict is not loaded correctly.
Use `self.load_state_dict` instead of `mmengine.runner.load_state_dict`
=> [Fix] Fix swin load state_dict

mmseg/models/data_preprocessor.py, mmseg/models/segmentors/base.py, tests/test_models/test_data_preprocessor.py
- Fix removing gt_sem_seg padding at postprocess_result
- Support  different padding methods in testing
- Add removing gt_sem_seg padding at postprocess_result method in mmseg/models/segmentors/base.py.
- Add test_cfg` params to SegDataPreprocessor, supporting different padding methods.
None
In a case that uses `size` in training and using `size_divisor` in testing, we might set the `test_cfg` param to data_preprocessor.
```python
data_preprocessor = dict(
type='SegDataPreProcessor',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
bgr_to_rgb=True,
pad_val=0,
seg_pad_val=255,
size=(512, 512),
test_cfg=dict(size_divisor=32))
```
=> [Enhancement] Support padding in testing

demo/MMSegmentation_Tutorial.ipynb
- It does not need to install torch again in this tutorial because users usually have installed torch following [get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/dev-1.x/docs/en/get_started.md#installation) , or use default environment on colab.
- The api `show_result_pyplot()` does not have the parameter `palette` .
- Save the bug `AttributeError: 'EncoderDecoder' object has no attribute 'dataset_meta'` in ` vis_result = show result pyplot(model, img, result, palette)` . The 'dataset_meta' is saved in the checkpoint.
- Remove the step of torch installation.
- Init the model from the checkpoint before inference and visualization.
- Remove the needless parameter `palette` in `show_result_pyplot(model, img, result, palette)` .
=> Fixe the bug in the visualization step.

.github/workflows/build.yml
=> [CI] Add torch1.13 checking in CI

data, mmseg/models/decode_heads/knet_head.py
Fix: https://github.com/open-mmlab/mmsegmentation/issues/2325
In latest dev-1.x branch, it would raise error when training K-Net like below:
After adding `self.out_channels = self.num_classes` in `IterativeDecodeHead` initialization function, this bug would be fixed:
=> [Fix] Fix KNet IterativeDecodeHead bug in dev-1.x branch

configs/_base_/models/deeplabv3_unet_s5-d16.py, configs/_base_/models/fcn_unet_s5-d16.py, configs/_base_/models/pspnet_unet_s5-d16.py
**Bug fix on _base_ U-Net scripts**: The base U-Net scripts contain some variables in wrong type in `test_cfg` dictionary. The `stride` and `crop_size` fields in this dict are supposed to be `tuples(int, int)`, however, they are `int` which result in the following exception at validation step:
```
h_stride, w_stride = self.test_cfg.stride TypeError: cannot unpack non-iterable int object
```
An issue is created …
=> BUG FIX in test_cfg for U-Net _base_ scripts

mmseg/models/decode_heads/knet_head.py
Fix: https://github.com/open-mmlab/mmsegmentation/issues/2325
In latest master branch, it would raise error when training K-Net like below:
After adding `self.out_channels = self.num_classes` in `IterativeDecodeHead` initialization function, this bug would be fixed:
=> [Fix] Fix KNet IterativeDecodeHead bug in master branch

mmseg/__init__.py, mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Support resize shortest edge while keeping the aspect ratio unchanged.
Modifed from https://github.com/facebookresearch/detectron2/blob/main/detectron2/data/transforms/augmentation_impl.py#L130
- Add `ResizeShortestEdge` to mmseg/datasets/transforms/transforms.py
- Add unit test
Depend on `mmcv >= 2.0.0rc3`
At `train_pipeline`:
```python
train_pipeline = [
...
dict(
type='RandomChoiceResize',
scales=[128, 256, 512],
resize_type='ResizeShortestEdge',
max_size=2048,
)
...
]
```
=> [Feature] Add ResizeShortestEdge transform

mmseg/datasets/ade.py, mmseg/datasets/chase_db1.py, mmseg/datasets/coco_stuff.py, mmseg/datasets/dark_zurich.py, mmseg/datasets/drive.py, mmseg/datasets/hrf.py, mmseg/datasets/isaid.py, mmseg/datasets/isprs.py, mmseg/datasets/lip.py, mmseg/datasets/loveda.py, mmseg/datasets/night_driving.py, mmseg/datasets/pascal_context.py, mmseg/datasets/potsdam.py, mmseg/datasets/stare.py, mmseg/datasets/voc.py
before this modification, the key-word arguments don't allow input, like
```python
class ADE20KDataset(BaseSegDataset):
def __init__(self, **kwargs) -> None:
super().__init__(
img_suffix='.jpg',
seg_map_suffix='.png',
reduce_zero_label=True,
**kwargs)
```
It would not allow `img_suffix` and `seg_map_suffix`, and raise `TypeError: __init__() got multiple values for keyword argument 'img_suffix'`
```python
ADE20KDataset(data_root = 'data/ade/ADEChallengeData2016',
...:     data_prefix=dict(img_path='images/training', …
```
=> [Fix]Add input argument for datasets

mmseg/models/decode_heads/decode_head.py
There is a typo in the seg_logits name and is missing backticks although it is a variable.
Fixed.
=> Fix typo in warning on binary classification

docs/en/user_guides/1_config.md, docs/zh_cn/user_guides/1_config.md
=> CodeCamp #144 [Doc] Chinese version of config tutorial

mmseg/core/hook/wandblogger_hook.py
Co-authored-by: WangYudong <yudong.wang@akane.waseda.jp>
Bug report on mmseg: https://github.com/open-mmlab/mmsegmentation/issues/2137
Bug report on mmdet: https://github.com/open-mmlab/mmdetection/issues/8145.
**deadlock occurs on both mmseg and mmdet, for the same reason.**
To summarize problem, when we use `MMSegWandbHook` after `TextLoggerHook`, deadlock problem occurs. These are because of same reason and I summarized the reason in https://github.com/open-mmlab/mmdetection/issues/8145#issuecomment-1345343076 here.
Made …
=> Fixed deadlock issue related with MMSegWandbHook

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml, projects/README.md, projects/example_project/README.md, projects/example_project/configs/fcn_dummy-r50-d8_4xb2-40k_cityscapes-512x1024.py, projects/example_project/dummy/__init__.py, projects/example_project/dummy/dummy_resnet.py
Introducing new models and features into OpenMMLab's algorithm libraries has long been complained to be troublesome due to the rigorous requirements on code quality, which could hinder the fast iteration of SOTA models and might discourage potential contributors from sharing their latest outcome here.
Ref: https://github.com/open-mmlab/mmocr/pull/1524 https://github.com/open-mmlab/mmocr/pull/1628
This PR adds a new `projects/` folder, which will be a place for some experimental models/features. Implementations inside might be not quite perfect but already fine to produce some exciting results. We hope that this PR can help us better embrace the contribution from our community. We also add the first example project to illustrate what we expect a good project to have.
=> [Projects] Add 'Projects/' folder, and the first example project

mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Add random crop for the biomedical image.
implement nnUNet random crop before data augmentation
1. Pre-commit or other linting tools are used to fix the potential lint …
=> [Feature] Add Biomedical 3D array random crop transform

docs/zh_cn/advanced_guides/engine.md
When refining PR: https://github.com/open-mmlab/mmsegmentation/pull/2169, I found some contents of PR2169 is useful but unnecessary to be added in customized runtime doc.
So I move some content to engine.doc
=> [Doc] Change some content from customize_runtime to engine ZN doc

mmseg/models/decode_heads/mask2former_head.py, mmseg/models/decode_heads/maskformer_head.py
Calling `mmseg.utils.register_all_modules` will import `MaskFormerHead` and `Mask2FormerHead`, it will crash if mmdet is not installed as `None` cannot be initialized.
- Modify `MMDET_MaskFormerHead=BaseModule` and `MMDET_Mask2FormerHead = BaseModule` when cannot import from mmdet
=> [Fix] Remove dependcy mmdet  when do not use `MaskFormerHead` and `MMDET_Mask2FormerHead`

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
The conflict is caused by:
The user requested torch==1.12.1+cpu
torchvision 0.13.0+cpu depends on torch==1.12.0
modify the torch==1.12.0+cpu
=> [Fix]Fix pt version for merge stage test

.github/workflows/build.yml, tests/test_metrics.py
1. numpy from 1.24 deprecated the aliases np.object, np.bool, np.float, np.complex, np.str, and np.int
https://numpy.org/devdocs/release/1.24.0-notes.html
2. timm needs to pytorch>=1.7, so ignore test timm in pytorch 1.5 and 1.6
3. Remove install pillow as it doesn't test torchvision < 0.5
1. np.float->np.float32
2. torch >= '1.7.0' -> matrix.torch != '1.5.1+cu101' && matrix.torch != '1.6.0+cu101' (as '1.10' < '1.7'
3. Remove install pillow
=> [Fix]Fix the deprecation of np.float and fix ci configuration

mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
implement nnUNet-style Gaussian Noise and Blur
1. Pre-commit or other linting tools are used to fix the …
=> [Feature] nnUNet-style Gaussian Noise and Blur

mmseg/datasets/pascal_context.py
The docstring in the class PascalContextDataset59 is misleading. Try to fix it.
The docstring in the class PascalContextDataset59 is changed.
1. Pre-commit or other linting …
=> Fix the docstring error in the class PascalContextDataset59

.github/workflows/build.yml, projects/README.md, projects/example_project/README.md, projects/example_project/configs/fcn_dummy-r50-d8_4xb2-40k_cityscapes-512x1024.py, projects/example_project/dummy/__init__.py, projects/example_project/dummy/dummy_resnet.py
Introducing new models and features into OpenMMLab's algorithm libraries has long been complained to be troublesome due to the rigorous requirements on code quality, which could hinder the fast iteration of SOTA models and might discourage potential contributors from sharing their latest outcome here.
Ref: https://github.com/open-mmlab/mmsegmentation/pull/2412
This PR adds a new `projects/` folder, which will be a place for some experimental models/features. Implementations inside might be not quite perfect but already fine to produce some exciting results. We hope that this PR can help us better embrace the contribution from our community. We also add the first example project to illustrate what we expect a good project to have.
=> [Projects] Add 'Projects/' folder, and the first example project in 0.x

mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Fix incorrect `img_shape` value assignment.
- mmseg/datasets/transforms/transforms.py
=> [Fix] Fix incorrect `img_shape` value assignment in RandomCrop

mmseg/datasets/transforms/formatting.py, mmseg/datasets/transforms/transforms.py, mmseg/utils/misc.py, tests/test_datasets/test_transform.py
The motivation of this PR is to add `gt_edge_map` field to support boundary loss.
- GenerateEdge
Modify `gt_edge` field to `gt_edge_map`.
- PackSegInputs
Add `gt_edge_map` to data_sample.
- stack_batch
Pad `gt_edge_map` to max_shape.
No
Reference `GenerateEdge`.
3. If the modification has potential influence on downstream projects, this …
=> [Feature] Add `gt_edge_map` field.

mmseg/core/evaluation/metrics.py, mmseg/datasets/pipelines/loading.py, tests/test_data/test_loading.py
I want to fix a bug through this PR. The bug occurs when two options -- `reduce_zero_label=True`, and custom classes are used. `reduce_zero_label` remaps the GT seg labels by remapping the zero-class to 255 which is ignored. Conceptually, this should occur *before* the `label_map` is applied, which maps *already reduced labels*. However, currently, the `label_map` is applied before the zero label is reduced.
The modification is simple:
- I've just interchanged the order of the two operations by moving 4 lines from bottom to top.
- I've added a test that passes when the fix is introduced, and fails on the original `master` branch.
I do not anticipate this change braking any backward-compatibility.
- _I've fixed all linting/pre-commit errors._
- _I've added a unit test._ 
- _I don't think …
=> [Fix] Switch order of `reduce_zero_label` and applying `label_map`

mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
Support for biomedical 3d images augmentation.
Add BioMedical3DRandomFlip in mmseg/datasets/transforms/transforms.py.
Add the function to support the flipping for biomedical 3d images and segmentation maps.
1. Pre-commit or other linting tools are used to fix the potential lint …
=> CodeCamp #141 [Feature] Add BioMedical3DRandomFlip.

mmseg/datasets/custom.py, tests/test_data/test_loading.py
This fixes #2493. When the `label_map` is created, the index for ignored classes was being set to -1, whereas the index that is actually ignored is 255. This worked indirectly since -1 was underflowed to 255 when converting to uint8.
The same fix was made in the 1.x by #2332 but this fix was never made to `master`.
The only small modification is setting the index of ignored classes to 255 instead of -1.
- _I've fixed all linting/pre-commit errors._
- _No unit tests need to be added. Unit tests that are affected were modified.
- _I don't think this change affects MMDet or MMDet3D._
- _This change fixes an existing bug and doesn't require modifying any documentation/docstring._
=> [Fix] Fix ignore class id from -1 to 255 in `master`

mmseg/core/evaluation/metrics.py, mmseg/datasets/custom.py, tests/test_data/test_dataset.py
Through this PR, I (1) fix a bug, and (2) perform some associated cleanup, and (3) add a unit test. The bug occurs during evaluation when two options -- `reduce_zero_label=True`, and custom classes are used. The bug was that the `reduce_zero_label` is not properly propagated (see details below).
1. **Bugfix**
The bug occurs [in the initialization of `CustomDataset`](https://github.com/open-mmlab/mmsegmentation/blob/5d49918b3c48df5544213562aa322bfa89d67ef1/mmseg/datasets/custom.py#L108-L110) where the `reduce_zero_label` flag is not propagated to its member `self.gt_seg_map_loader_cfg`:
```python
self.gt_seg_map_loader = LoadAnnotations(
) if gt_seg_map_loader_cfg is None else LoadAnnotations(
**gt_seg_map_loader_cfg)
```
Because the `reduce_zero_label` flag was not being propagated, the …
=> [Fix] Fix `reduce_zero_label` in evaluation

mmseg/datasets/transforms/loading.py, tests/test_datasets/test_loading.py
This is an almost exact duplicate of #2500 (that was made to the `master` branch) now applied to the `1.x` branch.
---
I want to fix a bug through this PR. The bug occurs when two options -- `reduce_zero_label=True`, and custom classes are used. `reduce_zero_label` remaps the GT seg labels by remapping the zero-class to 255 which is ignored. Conceptually, this should occur *before* the `label_map` is applied, which maps *already reduced labels*. However, currently, the `label_map` is applied before the zero label is reduced.
The modification is simple:
- I've just interchanged the order of the two operations by moving a few lines from bottom to top.
- I've added a test that passes when the fix is introduced, and fails on the original `master` branch.
I do not anticipate this change …
=> [Fix] Switch order of `reduce_zero_label` and applying `label_map` in 1.x

mmseg/datasets/basesegdataset.py
This is motivated by a previously unfinished PR (#2332). In that PR, the label -1 was changed to 255 in `BaseSegDataset`, which is correct. However, it was changed at only one location. There is another location in `mmseg/datasets/basesegdataset.py` where -1 was still being used that was not converted to 255. I have now converted it to 255.
This is exactly same as a similar fix to the `master` branch via #2515 .
I've simply converted the snipped
```python
if new_id != -1:
new_palette.append(palette[old_id])
```
to 
```python
if new_id != 255:
new_palette.append(palette[old_id])
```
- _I've fixed all linting/pre-commit errors._
- _No unit tests need to be added or were affected.
- _I don't think this change affects MMDet or MMDet3D._
- _This change fixes an existing bug and doesn't require …
=> [Fix] Unfinished label conversion from `-1` to `255` in 1.x

mmseg/models/losses/cross_entropy_loss.py
The documentation of the use_sigmoid argument in CrossEntropyLoss currently suggests the sigmoid would be applied in addition to the softmax function. This change fixes this typo.
=> change typo in CrossEntropyLoss

mmseg/models/decode_heads/decode_head.py, mmseg/models/segmentors/base.py, mmseg/models/segmentors/cascade_encoder_decoder.py, mmseg/models/segmentors/encoder_decoder.py
A few functions in the following files:
- `decode_head.py`
- `encoder_decoder.py`
- `cascade_encoder_decoder.py`
have a return type annotation as `List[Tensor]` whereas their actual return type is `Tensor`. This can be seen by following the trace of what each functions return internally, which eventually leads to `seg_logits: Tensor`.
This type annotation is misleading and confusing when a user is trying to read and understand the code.
1. Fix type annotations from `List[Tensor]` to `Tensor`.
2. Make a return type more specific from `list` to `SampleList`.
- _I've fixed all linting/pre-commit errors._
- _This involves only changing type annotations, so there is no need for tests._ 
- _I don't think this change affects MMDet or MMDet3D._
- _This change fixes existing type annotations, so …
=> [Types] Fix misleading `List[Tensor]` types

mmseg/models/decode_heads/decode_head.py, mmseg/models/segmentors/base.py, mmseg/models/segmentors/cascade_encoder_decoder.py, mmseg/models/segmentors/encoder_decoder.py
This is essentially #2535 that I had intended to submit to the `dev-1.x` branch but accidentally submitted it directly to the `1.x` branch (apologies!). This also got approved possibly because the core devs also didn't realize this.
The problem is that now `1.x` and `dev-1.x` are out of sync -- the changes introduced by #2535 will never be reflected in `dev-1.x`.
I'm proposing this "backward-merge" so that `1.x` and `dev-1.x` can be in sync again. If you look at "files changed", they are exactly the changes introduced by #2535.
=> Backward merge #2535 from `1.x` into `dev-1.x`

docs/en/advanced_guides/customize_runtime.md
Translate Chinese version customized runtime doc into English https://github.com/open-mmlab/mmsegmentation/pull/2502.
=> [Doc] Add EN custmized runtime doc in dev-1.x

configs/_base_/datasets/ade20k.py, configs/_base_/datasets/ade20k_640x640.py, configs/_base_/datasets/chase_db1.py, configs/_base_/datasets/cityscapes.py, configs/_base_/datasets/coco-stuff10k.py, configs/_base_/datasets/coco-stuff164k.py, configs/_base_/datasets/drive.py, configs/_base_/datasets/hrf.py, configs/_base_/datasets/isaid.py, configs/_base_/datasets/loveda.py, configs/_base_/datasets/pascal_context_59.py, configs/_base_/datasets/pascal_voc12.py, configs/_base_/datasets/pascal_voc12_aug.py, configs/_base_/datasets/potsdam.py, configs/_base_/datasets/stare.py, configs/_base_/datasets/vaihingen.py, docs/en/migration/interface.md, mmseg/datasets/basesegdataset.py, mmseg/datasets/transforms/loading.py, mmseg/engine/hooks/visualization_hook.py, tests/test_datasets/test_loading.py
In MMEngine >= 0.2.0, it might directly determine what the backend is by using the `data_root` path.
All default `backend_args` values.
=> [FIx] Set default `backend_args` values to None

docs/en/notes/faq.md, requirements/mminstall.txt
As the mmdet and mmcls are not very stabel, and mim can install repo from source code, we remove them from mminstall and  they won't be installed automatically when run `mim install mmsegmentation`
1. remove mmdet and mcls from mminstall
2. add explanation in faq
=> [Enhancement] Remove mmdet and mmcls from mminstall

tools/analysis_tools/browse_dataset.py
browse_dataset before training
create tools/analysis_tools/browse_dataset.py
2. The …
=> tools/analysis_tools browse_dataset.py

configs/segnext/README.md, configs/segnext/segnext_mscan-b_1x16_512x512_adamw_160k_ade20k.py, configs/segnext/segnext_mscan-l_1x16_512x512_adamw_160k_ade20k.py, configs/segnext/segnext_mscan-s_1x16_512x512_adamw_160k_ade20k.py, configs/segnext/segnext_mscan-t_1x16_512x512_adamw_160k_ade20k.py
Transfer keys of each `mscan_x.pth` pretrained models of SegNeXt, and upload them in the website.
The reason of transferring keys is we modify original repo [`.dwconv.dwconv.xxx`](https://github.com/Visual-Attention-Network/SegNeXt/blob/main/mmseg/models/backbones/mscan.py#L21) to [`.dwconv.xxx`](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/mscan.py#L43).
=> [Fix] Fix pretrained models of SegNeXt in master branch.

mmseg/evaluation/__init__.py, mmseg/evaluation/metrics/__init__.py, mmseg/evaluation/metrics/citys_metric.py, tests/test_evaluation/test_metrics/test_citys_metric.py
=> [Fix] Support format_result and fix prefix param in cityscape metric, and rename CitysMetric to CityscapesMetric

docs/en/advanced_guides/transforms.md, docs/zh_cn/advanced_guides/transforms.md
=> [Doc] Add zh_cn transforms doc and format en doc

tools/analysis_tools/get_flops.py
=> [Feature] Support calculating FLOPs of segmentors

mmseg/datasets/transforms/formatting.py, tests/test_datasets/test_formatting.py
fix #2593
1. Only when gt seg map is 2D, extend its shape to 3D PixelData 
2. If seg map is not 2D, we raised warning for users.
=> [Enhancement] Support input gt seg map is not 2D

mmseg/datasets/dataset_wrappers.py, mmseg/datasets/transforms/transforms.py, projects/mapillary_dataset/tools/dataset_converters/mapillary.py
I just replaced the `indexes` variable name with `indices` for naming consistency.
=> [Typo] Change indexes to indices

mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
I changed the hardcoded 3 channel length to dynamic channel length in `np.full` function arguments.
This modification enables `RandomMosaic` transform to support multispectral image (e.g. RGB image with NIR band) or bi-temporal image pairs for change detection task.
If so, please describe how it breaks the compatibility and how the …
=> [Enhance] Support multi-band image for Mosaic

mmseg/apis/train.py, mmseg/utils/util_distribution.py, tests/test_utils/test_util_distribution.py
Added ascending device support in mmseg.
The main modification points are as follows:
We added an NPU device in the DDP scenario and DP scenario when using the NPU.
None
We tested [fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/mast …
=> [Feature] Support mmseg with NPU backend.

docs/en/advanced_guides/engine.md, docs/zh_cn/advanced_guides/engine.md
As title.
- docs/en/advanced_guides/engine.md
=> [Doc] Add English version document of the Training Engine

tools/test.py, tools/train.py
As title.
Ref: https://github.com/open-mmlab/mmediting/pull/1712
=> [Fix] Fix accepting an unexpected argument `local-rank` in PyTorch 2.0

MANIFEST.in
=> [Fix] Fix manifest

mmseg/registry/registry.py
If the module does not actually exist, setting locations will report an error.
https://github.com/open-mmlab/mmengine/pull/1010
mmseg/registry/registry.py
=> [Fix] Remove locations of not exists modules in the registry

mmseg/models/decode_heads/ham_head.py
```
Traceback (most recent call last):
File "/Users/kkieek/Workspace/mmsegmentation/tools/train.py", line 104, in <module>
main()
File "/Users/kkieek/Workspace/mmsegmentation/tools/train.py", line 100, in main
runner.train()
File "/Users/kkieek/Workspace/mmsegmentation/.env/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1686, in train
model = self.train_loop.run()  # type: ignore
File "/Users/kkieek/Workspace/mmsegmentation/.env/lib/python3.9/site-packages/mmengine/runner/loops.py", line 264, in run …
```
=> [Refactor] Handle case where device is neither CPU nor CUDA in HamHead

.circleci/test.yml, mmseg/datasets/__init__.py, mmseg/datasets/transforms/__init__.py, mmseg/datasets/transforms/transforms.py, tests/test_datasets/test_transform.py
https://github.com/open-mmlab/mmsegmentation/blob/3a14c3597418d3e6eb64a3c65044fcf91f0c105d/mmseg/datasets/pipelines/transforms.py#L1348
Add albu to dev-1.x
=> [Feature] Support albu transform

docs/en/user_guides/visualization_feature_map.md
Motivation
Typo in docs/en/user_guides/visualization_feature_map.md.
Modification
reature -> feature
Checklist
=> Fix typo in docs/en/user_guides/visualization_feature_map.md

README.md, README_zh-CN.md, mmseg/models/decode_heads/decode_head.py
The out_channels is default to None, but the args didn't point this out.
Just a small change in Arg instrutions.
=> [Doc] Fix a tiny mis-Arg in BaseDecodeHead class

README.md, README_zh-CN.md, mmseg/datasets/basesegdataset.py
While customizing the number of samples using `ann_file` for Cityscapes, I noticed that when the `ann_file` name is incorrect, it will silently resort to loading the dataset from the directory.
I think when the user intends to load using `ann_file`, it should not silently fail, but give some sort of error message or warning.
I added assertion to check whether the `ann_file` …
=> Prevent passed `ann_file` from silently failing to load

mmseg/models/losses/tversky_loss.py, tests/test_models/test_losses/test_tversky_loss.py
The focal Tversky loss was proposed in https://arxiv.org/abs/1810.07842. It has nearly 600 citations and has been shown to be extremely useful for highly imbalanced (medical) datasets. To add support for the focal Tversky loss, only few lines of changes are needed for the Tversky loss.
Add `gamma` as (optional) argument in the constructor of `TverskyLoss`. This parameter is then passed to `tversky_loss` to compute the focal Tversky loss. 
Does the modification introduce changes that break the backward-compatibility of the …
=> [Feature] Add support for the focal Tversky loss

README.md, README_zh-CN.md, tools/dataset_converters/isaid.py
When processing data in the isaid experiment, generated images only have binary pixel values of 0 or 1 instead of the corresponding class values. This causes significant interference and prevents subsequent experiments from proceeding. After investigation, it was found that the issue was caused by using the wrong image format for saving the images. Saving the images as PNG resulted in binary pixel values, while saving the images as BMP resolved the issue and correctly saved the class values.
`img_patch.save(save_path_image, format='BMP')`
This code will save the image data as BMP format.
Confirm that the modification does not introduce new issues and test that the modified code successfully resolves the original problem.
=> Fixes an issue in isaid.py

mmseg/apis/train.py, mmseg/utils/__init__.py, mmseg/utils/util_distribution.py
We will support full precision training on the next generation Ascend NPU, so there is no need to enable mixed precision by default.
Determine whether the current chip supports full precision training, and automatically enable mixed precision.
Not affected.
We have verified the correctness on the Ascend NPU.
=> [Enhance] Enable full precision training on Ascend NPU.

README.md, README_zh-CN.md, mmseg/datasets/basesegdataset.py
Suppose an image is named `jpg.jpg` and its corresponding segmap is named `jpg.png`.
The original implementation will try to read segmap from `png.png` and causes FileNotfoundError
Only replace the suffix, instead of full string search and replacement. 
Probably no. 
=> [Fix] Robust mapping from image path to seg map path

configs/_base_/datasets/coco-stuff164k.py
=> [Fix] Fix train map path for coco-stuff164k.py

mmseg/apis/train.py
Address an issue where mix training is not enabled when optimizer_config is present in the config on Ascend NPU
Previously, mix training was not enabled when optimizer_config was present in the configuration on Ascend NPU. This commit addresses the issue by ensuring that mix training is enabled under these circumstances.
It has been validated on the knet_s3_upernet_swin-l_8x2_640x640_adamw_80k_ade20k.py config.
4. The documentation has been modified …
=> [Fix] Fix mix training on Ascend NPU

mmseg/apis/inference.py, mmseg/utils/__init__.py, mmseg/visualization/local_visualizer.py
[Add semantic label to the segmentation visualization results 分割可视化结果中加上语义信息 #154](https://github.com/open-mmlab/OpenMMLabCamp/discussions/154)
corresponding issue:  [跑出来结果之后怎么在结果图片上获取各个语意部分的区域信息？ #2578](https://github.com/open-mmlab/mmsegmentation/issues/2578)
1. mmseg/apis/inference.py,  add withLabels in visualizer.add_datasample call, to indicate whether add semantic label
2. mmseg/visualization/local_visualizer.py,  add semantic labels by opencv; modify the demo comment description 
3. mmseg/utils/__init__.py,  add bdd100k …
=> [CodeCamp2023-154] Add semantic label to the segmentation visualization results

mmseg/datasets/pascal_context.py
-  'PascalContextDataset' object has no attribute 'file_client', it will cause an error. 
-  The attribute ‘ann_file’ is not allowed to be empty, otherwise, an error will be reported.
- Replace file_client with fileio
=> [Fix] Fix module PascalContextDataset

mmseg/models/losses/dice_loss.py, tests/test_models/test_losses/test_dice_loss.py
Added ignore_index param to forward(),
also implemented one hot encoding to ensure the dims of target matches pred.
Attempted to solve the problems mentioned by #3172 
Added ignore_index into forward function (although the dice loss itself does not actually take account for it for some reason).
Added _expand_onehot_labels_dice, which takes the target with shape [N, H, W] into …
=> [Fix] Added ignore_index and one hot encoding for dice loss

docs/en/get_started.md, docs/zh_cn/get_started.md
there is a code mistake in `docs\zh_cn\get_started.md` and `docs\en\get_started.md`,it use the 0.x api,which is changed in 1.x
`docs\zh_cn\get_started.md` ,`docs\en\get_started.md`
fix inference_segmentor --> inference_model
If this PR introduces a new feature, it is better to list …
=> [Doc]fix inference_segmentor to inference_model

docs/en/user_guides/5_deployment.md, docs/zh_cn/user_guides/5_deployment.md
translate doc for docs/zh_cn/user_guides/5_deployment.md
update `docs/en/user_guides/5_deployment.md`
fix `docs/zh_cn/user_guides/5_deployment.md`
1. Pre-commit or other …
=> [Doc]translate doc for docs/zh_cn/user_guides/5_deployment.md

mmseg/evaluation/__init__.py, mmseg/evaluation/metrics/__init__.py, mmseg/evaluation/metrics/depth_metric.py, mmseg/utils/io.py, tests/test_evaluation/test_metrics/test_depth_metric.py
Support metrics for the depth estimation task, including RMSE, ABSRel, and etc.
Using the following configuration to compute …
=> [Feature] Support depth metrics

tools/analysis_tools/visualization_cam.py
Use the pytorch-grad-cam tool to visualize Class Activation Maps (CAM).
Use the pytorch-grad-cam tool to visualize Class Activation Maps (CAM).
requirement: pip install grad-cam
run commad: python tools/analysis_tools/visualization_cam.py
If this PR introduces a new feature, it is …
=> Use the pytorch-grad-cam tool to visualize Class Activation Maps (CAM)

MANIFEST.in
https://github.com/open-mmlab/mmsegmentation/issues/3383
- Add bpe_simple_vocab_16e6.txt.gz to `MANIFEST.in`
=> [Fix] Add bpe_simple_vocab_16e6.txt.gz to release

mmseg/models/decode_heads/decode_head.py, mmseg/models/decode_heads/san_head.py, projects/hssn/decode_head/sep_aspp_contrast_head.py
When using `test_cfg` for `data_preprocessor`, `predict_by_feat` resizes to the original size, not the padded size.
```
data_preprocessor = dict(
type="SegDataPreProcessor",
#type="SegDataPreProcessorWithPad",
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
bgr_to_rgb=True,
pad_val=0,
seg_pad_val=255,
test_cfg=dict(size=(128, 128)))
```
Refar to:
https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/models/decode_heads/san_head.py#L589-L592
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or …
=> [Bugfix] test resize with pad_shape

demo/image_demo.py, demo/image_demo_with_inferencer.py, mmseg/apis/inference.py, mmseg/apis/mmseg_inferencer.py, mmseg/visualization/local_visualizer.py
It is difficult to visualize without "labels" when using the inferencer.
- While using the `MMSegInferencer`, the visualized prediction contains labels on the mask, but it is difficult to pass `withLabels=False` without rewriting the config (which is harder to do when you initialize the inferencer with a model name rather than the config).
- I thought it would be easier to just pass `withLabels=False` to `inferencer.__call__()` since you can also pass `opacity` and other parameters anyway. 
Please briefly describe what …
=> [Feature] add -with-labels arg to inferencer for visualization without labels

tools/analysis_tools/get_flops.py
`inputs` and `input_shape` can't be both set to mmengine api `get_model_complexity_info`
https://github.com/open-mmlab/mmengine/pull/1056
Set `input_shape` to None.
=> [Fix] Fix get_flops scrip

mmseg/models/decode_heads/decode_head.py, mmseg/models/decode_heads/enc_head.py, mmseg/models/decode_heads/vpd_depth_head.py
Use `MODELS.build` instead of `build_loss`
=> [Fix] update build loss api

mmseg/engine/hooks/visualization_hook.py, tests/test_engine/test_visualization_hook.py
The current `SegVisualizationHook` implements the `_after_iter` method, which is invoked during the validation and testing pipelines. However, when in [test_mode](https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/engine/hooks/visualization_hook.py#L97), the implementation attempts to access `runner.iter`. This attribute is defined in the [`mmengine` codebase](https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L538) and is designed to return `train_loop.iter`. Accessing this property during testing can be problematic, particularly in scenarios where the model is being evaluated post-training, without initiating a training loop. This can lead to a crash if the implementation tries to build a training dataset for which the annotation file is unavailable at …
=> [Fix] bugfix/avoid-runner-iter-in-vis-hook-test-mode  
